### ISSUE TITLE
[questions/qa-personal-names]  

### ISSUE THREAD

**Issue by quiddity-wp** [w3c/i18n-drafts#102]
[source] (https://www.w3.org/International/questions/qa-personal-names) [en]

I suggest adding this link to the Further Reading section: http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by r12a** [comment]
Thanks for the suggestion. However, we're quite conservative about what we add to the Further Reading selection, so i prefer not to add this link.

**Comment by quiddity-wp** [comment]
Hi. That makes sense. 

FYI, a newer response to that blog post came out a few months after I left the original suggestion. The response includes examples! https://shinesolutions.com/2018/01/08/falsehoods-programmers-believe-about-names-with-examples/ 

Suggestion: I wonder if it would be useful to add a link to that newer post, into the wikipage at https://www.w3.org/International/wiki/Personal_names which the draft itself already links to? I cannot create an account on that wiki (I'm not on a working group), else I would boldly do so. 
Hope that helps, and thanks for working on this regardless. :-)

**Comment by r12a** [comment]
I added the link to https://www.w3.org/International/wiki/Personal_names#Other_articles. Thanks!
