### ISSUE TITLE
[articles/strings-and-bidi/index] Minor proof-reading edits

### ISSUE THREAD

**Issue by huijing** [w3c/i18n-drafts#104]
[source] (https://w3c.github.io/i18n-drafts/articles/strings-and-bidi/index.en#survey) [en]

This article illustrates problems that can arise when strings are inserted into text and then displayed to users ~~given~~ *in* different directional contexts: left-to-right (LTR) vs. right-to-left (RTL).

~~The strings we'll use are the data for one record representing a book. Here they are:~~ *For this example, the strings used are data from a single book record, as follows:*

Here we take the strings, programmatically, and simply add them ~~to~~ *as* span elements ~~in~~ to an HTML template for viewing by a British user.

The title of the book in the ~~arabic~~ *Arabic* translation should read: CSS: مغامرة جديدة! , and the same applies to the ~~persian~~ *Persian* and ~~hebrew~~ *Hebrew* translations. Note how the text 'CSS' should appear on the right of the ~~arabic~~ *Arabic* text, and the exclamation mark should appear at the far left of the title.

...the surrounding ~~english~~ *English* context...

You can see that the ~~arabic~~ *Arabic*, ~~persian~~ *Persian* and ~~hebrew~~ *Hebrew* translations of the book title (in the bulleted list) ~~now look~~ *are now displayed* as expected, since they inherit the base direction of the card (RTL).

However, in ~~a RTL overall~~ *an overall RTL* context this list should be ordered right-to-left.

and the bidi algorithm produces them that way by default after a ~~hebrew~~ *Hebrew* character.

It's not relevant here ~~that~~ *as* purely numeric dates are ~~never usually~~ *usually never* a good idea...have prevented any ordering ~~issue~~ *issues*.

The order of the words and the exclamation mark in the ~~arabic~~ *Arabic*, ~~persian~~ *Persian* and ~~hebrew~~ *Hebrew* titles is now wrong.

...examining the direction of the first *strong-directional* character...

...the base direction for this ~~isolation~~ *isolated* segment...

...isolated from the preceding ~~arabic~~ *Arabic* text...

...the context is that of the ~~arabic~~ *Arabic* language.

The date is still in the wrong order for ~~arabic~~ *Arabic* language readers.

...we changed the ~~javascript~~ *Javascript* code that does the display so that...an invisible ~~arabic~~ *Arabic* character

For the purpose of the example above, we need to read ~~in~~ *from* a different JSON file.

This now becomes the first *strong-directional* character

The second strategy was used for the ~~persian~~ *Persian* and ~~hebrew~~ *Hebrew* translations, ~~and was to add~~ a direction property *was added* to the object containing the string. ...and is read by the ~~javascript~~ *the Javascript* ~~as it~~ *which* fills in the template.

Putting an RLM at the start of a string that would otherwise be incorrectly interpreted, seems *like* a simple fix.

..the existence of the *direction-value* pair,

**Comment by r12a** [comment]
@huijing thanks for these suggestions. I adopted most of them.  

I'm not a fan of unnecessary capitalisation, so i prefer to write the language Arabic (where Arabic is a noun), but the arabic language (where arabic is an adjective).  I'm leaving it that way unless i get further pushback. (I'm not particularly interested in following rules unless there are practical reasons for them.)

First strong directional is an interesting one. Sometimes you see first-strong, as in 'first-strong' heuristics. But in the Unicode Standard there is no hyphen for first strong directional character, and that's the lead i followed.

There were a couple of proposals that changed the meaning away from what i intended, so i didn't adopt those. An interesting one was 'direction value pair'. I see this as a value-pair associated with direction, so i put the hyphen between value and pair.

If you think i should make more changes, please reopen this issue. Thanks.

**Comment by huijing** [comment]
I agree with your approach. Thank you for accepting the edits.
