### ISSUE TITLE
[articles/strings-and-bidi/index] editorial: "usually never"

### ISSUE THREAD

**Issue by matial** [w3c/i18n-drafts#105]
[source] (http://w3c.github.io/i18n-drafts/articles/strings-and-bidi/index.en) [en]

In the paragraph "A brief note concerning dates" we find the expression "usually never". It looks to me like an oxymoron..

**Comment by r12a** [comment]
That is probably definitely a good point. I fixed it at https://github.com/w3c/i18n-drafts/commit/5beb2ff3b767d0bffa59f143abf564395d31b934
