### ISSUE TITLE
[articles/strings-and-bidi/index] Transcriptions not clear

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-drafts#107]
[source] (http://w3c.github.io/i18n-drafts/articles/strings-and-bidi/index.en.html#third) [en]

> from Mati Allouche:

In the last paragraph you write: "this may be a Latin transcription of a non-Latin string"

I am not sure that I understand the problem. The language being Hebrew, which is generally written in a RTL script, we can guess that the required direction is RTL. If there are such Latin transcriptions within Hebrew-script text, they should be treated just like actual English, French or Greek phrases included within a generally Hebrew text.

There could be a problem if all the Hebrew content is written as Latin transcription. In this case, the "lang":"he" may do more harm than good. If this is your intended use case, it should be more explicit, and the word "string" does not convey the idea.

I suggest:
"this may be a Latin transcription (to be written left to right) of a unit of text in a language usually written with a RTL script, so that deriving the direction from the declared language does not indicate correctly how the Latin transcription should be written."
Note that I have written "unit of text" instead of "string". I am not sure this is the best term. Something more specific like "paragraph" might be preferred.

**Comment by r12a** [comment]
> There could be a problem if all the Hebrew content is written as Latin transcription.

Yes, that's what i'm talking about there, not about multiple languages within a string (that was ruled out of scope for this article).  Perhaps it's actually the earlier part of the sentence that caused confusion.  I rewrote the paragraph. The mention of transcription is meant to capture strings in Hebrew but written with the Latin script, which you would hope would be labelled he-Latn (as Martin said).

We are here only concerned with strings (eg. what you'd find in JSON files, or CSV, or plain text data formats such as annotations, error messages, etc.), ie. quote delimited runs of text.  And we're concerned only with the base direction that should be applied to that string as a whole. 

Hope that's clearer.

**Comment by matial** [comment]
I can see the light now, thanks!
