### ISSUE TITLE
[questions/qa-floating-times] example typo?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-drafts#110]
[source] (https://w3c.github.io/i18n-drafts/questions/qa-floating-times.en) [en]

> Sat Apr 29 21:00:00 ART 2017

Shouldn't the format of that be more like the following (though corrected for the right locale)?

Wed Aug 30 2017 14:40:07 GMT+0100 (BST)

**Comment by aphillips** [comment]
Not necessarily. However I updated the examples using the current FF implementation. ART is the correct abbreviation for Argentina time.

**Comment by r12a** [comment]
Looks like this is addressed.
