### ISSUE TITLE
[questions/qa-http-and-lang]  

### ISSUE THREAD

**Issue by CecilWard** [w3c/i18n-drafts#125]
[source] (https://www.w3.org/International/questions/qa-http-and-lang) [en]

Accessibility feedback: the text in the above web page is extremely uncomfortably HUGE on my ipad pro in safari 11.1. It is really hurting my brain a lot. (I have cognitive deficits due to ME/CFS and bucket loads of pain drugs, and that lot doesn't help matters much either.) I know it's stupid Safari ios' fault for not being customisable at all, and it doesn't support user stylesheets. I'm in landscape mode which makes things even worse.

Any chance of keeping text down to a sensible size? (Advanced media queries etc if necessary) Could you, if this is even possible, keep the text the same physical size in both landscape and portrait modes?

(Aside: Some people are now offering a feature where they will serve up all pages with a user's choice of custom stylesheet. Any chance of W3C considering that? I realise it would cost. I think the wikimedia people do it, iirc. I have a router that does it for its web admin ui.)

**Comment by r12a** [comment]
@CecilWard we introduced the current size to improve accessibility. I only have an ordinary iPad, but the size, though bigger, does not seem so bad on that in landscape mode.  Have you zoomed in to the column width? Try two-finger pinch to make the text smaller. Rotating to vertical may also help, of course.

I don't know how to use the advanced media queries to produce the effect you mention, so if you do, or know someone who does, please let me know.  Having said that, sometimes i like to rotate to landscape on my iPad to make the text easier to read...

**Comment by xfq** [comment]
Maybe we can use [CSS lock](https://fvsch.com/code/css-locks/) to scale the font size linearly with screen width and clamp the font size to keep it within a reasonable range.

**Comment by r12a** [comment]
Closing this until we have more information.
