### ISSUE TITLE
[tutorials/bidi-xhtml/index]  

### ISSUE THREAD

**Issue by nicholaspretorius** [w3c/i18n-drafts#127]
[source] (https://www.w3.org/International/tutorials/bidi-xhtml/) [en]

Good day, 

The link to article in Further Reading returns a 503 Error: https://www.w3.org/International/techniques/authoring-html#direction

![image](https://user-images.githubusercontent.com/805497/33429073-fecd779c-d5d3-11e7-9420-c5029cd2715f.png)

**Comment by r12a** [comment]
This was due to a network outage at MIT. Should be fine now.
