### ISSUE TITLE
[tutorials/bidi-xhtml/index]  

### ISSUE THREAD

**Issue by nicholaspretorius** [w3c/i18n-drafts#128]
[source] (https://www.w3.org/International/tutorials/bidi-xhtml/) [en]

Good day, 

This one also returns a 503: https://www.w3.org/International/articles/inline-bidi-markup/uba-basics 

![image](https://user-images.githubusercontent.com/805497/33429215-8dc8ef8a-d5d4-11e7-9337-2a3941caffbd.png)

**Comment by r12a** [comment]
Thanks @nicholaspretorius .  There are currently network issues at MIT.  Hopefully it will work again soon. 

Btw, if you want to read the stuff about inline bidi in html you may want to try reading the version of that i'm currently in the process of updating at http://w3c.github.io/i18n-drafts/articles/inline-bidi-markup/index.en

**Comment by r12a** [comment]
Seems to be working again now.
