### ISSUE TITLE
[articles/ruby/index]  

### ISSUE THREAD

**Issue by arlelommel** [w3c/i18n-drafts#13]
It appears that the links at the bottom for “Using ruby markup” and “Styling ruby text” lead to 404s. Other than that, this looks very nice and comprehensive.

[source](http://w3c.github.io/i18n-drafts/articles/ruby/index.en) [en]

**Comment by r12a** [comment]
Thanks, Arle. I just sent a follow on note about the links – it's because the review doc is not on the w3c site.  I'll check them all before final publication, which will be on the w3c site, so they should all work.  Sorry i wasn't as fast as you :-)
