### ISSUE TITLE
[questions/qa-bidi-unicode-controls]  

### ISSUE THREAD

**Issue by faceless2** [w3c/i18n-drafts#131]
[source] (https://www.w3.org/International/questions/qa-bidi-unicode-controls) [en]

I believe the first example after the heading "TIGHTLY WRAPPING OPPOSITE-DIRECTION PHRASES" is invalid:
````
the title is &#x202B;AN INTRODUCTION TO &#x202C;c++&pdf;&pdf; in arabic.
````
202C is a PDF - I presume you're trying to insert an LRE, so it should be 202A.

**Comment by aphillips** [comment]
The capital letters are meant to illustrate right-to-left text, I believe, so RLE would be correct.

**Comment by faceless2** [comment]
No, I don't think that's correct - I'm not referring to the first markup character, but the second. I believe the intention was
````
the title is &rle;AN INTRODUCTION TO &lre;c++&pdf;&pdf; in arabic.
````
but what is actually in the example is
````
the title is &rle;AN INTRODUCTION TO &pdf;c++&pdf;&pdf; in arabic.
````
The incorrect markup character is the second, which is quoting the english word "c++" embedded in arabic; it should be LRE, which is 202A

**Comment by r12a** [comment]
@faceless2 is correct. I'll make the edit when i get a moment.

**Comment by r12a** [comment]
Fixed. Thanks for the report !   I do wish we could write &lre; instead but we were never able to convince the HTML editors that that was useful.
