### ISSUE TITLE
Feedback on tutorials/svg-tiny-bidi/Overview

### ISSUE THREAD

**Issue by Olasyar** [w3c/i18n-drafts#136]
[source] (http://www.w3.org/International/tutorials/svg-tiny-bidi/Overview.en.php) [en]

Hello my name is Olasyar,  I want to say that I tried to write just simply welcome in Pashto language but I saw the word's like (ډ), (ښ), (ې), (ڼ), (ټ), (ړ),( ۍ) and (ګ) are not part of svg alphabet system here please help us with this all of the words are very important to Pashto language. and some information I found here: https://www.w3.org/International/tutorials/svg-tiny-bidi/ but didn't helped me thank you very much

**Comment by r12a** [comment]
@Olasyar i'm not sure what your problem is, since SVG supports all Unicode characters (which includes those you mention).  I wonder whether the application you are using to create/display SVG is the thing that has limitations ?

**Comment by Olasyar** [comment]
@r12a  [https://commons.wikimedia.org/wiki/File:Welcome_psw.svg](url)

**Comment by Olasyar** [comment]
@r12a  look at this: https://commons.wikimedia.org/wiki/File:Welcome_psw.svg
here is 3 words which was actually not acceptable to svg system
(ښ),( ې), (ډ)

**Comment by r12a** [comment]
To solve that problem, you need to apply a font to the svg text that has the correct glyphs for all those characters before creating the png image. You can try Scheherazade, or Amiri, which can be downloaded for free. (I tried it out, and it works, with those fonts, however there are many fonts that don't do correct joining for ې.)
