### ISSUE TITLE
Feedback on questions/qa-i18n

### ISSUE THREAD

**Issue by mtsgeneroso** [w3c/i18n-drafts#137]
[source] (http://www.w3.org/International/questions/qa-i18n.pt-br.php) [pt-br]

The section "[Internaciolização](https://www.w3.org/International/questions/qa-i18n.pt-br#i18n)" has a mistake:

No inglês, "internacionalização" (internationalization) é, geralmente, referenciada como i18n, onde 18 é o número de letras entre o **'L'** e o **'N'**. 

Correct to: 
No inglês, "internacionalização" (internationalization) é, geralmente, referenciada como i18n, onde 18 é o número de letras entre o **'i'** e o **'n'**.

**Comment by r12a** [comment]
Fixed. Thank you.
