### ISSUE TITLE
[articles/ruby/index] The example of pinyin ruby

### ISSUE THREAD

**Issue by upsuper** [w3c/i18n-drafts#15]
[source](http://w3c.github.io/i18n-drafts/articles/ruby/index.en) [en]

It seems to me pinyin being above the base text is far more common than being below. I am not even aware of any example which mark pinyin below the text before.

Also, pinyin is usually marked with tone marks. So in that example, it should be "zhōng guó huà" instead.

**Comment by r12a** [comment]
thanks for the comment, Xidorn. I agree actually - it's from an old picture. I'll redo it.  I have seen pinyin below the line (the only example i can find quickly is the moedict site), but i agree that the majority is above. [reminder to myself, to colour it red too, like the other examples]
