### ISSUE TITLE
[articles/typography/linebreak]  Comment on S E Asian script line breaking

### ISSUE THREAD

**Issue by jmdurdin** [w3c/i18n-drafts#155]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]
"It has been suggested that the Unicode character U+200B ZERO WIDTH SPACE could be useful to indicate word boundaries, but people writing these languages don’t use it."
For Lao, especially in Lao PDR, this was quite widely used for many years before platforms implemented line breaking at a system level, supported by freely available application software distributed with the most commonly used Lao fonts.

**Comment by r12a** [comment]
Thanks for the comment! Made changes to the article.
