### ISSUE TITLE
[articles/typography/linebreak]  Ethiopic line wrapping with word separator

### ISSUE THREAD

**Issue by dyacob** [w3c/i18n-drafts#156]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

The statement:

_Ethiopic still wraps text a word at a time,_

I think needs some clarification and mention of an implicit(?) hyphenation practice. The above is a rule to follow when hyphenation is disabled in an electronic document.  However, I believe that users accustomed to the the Ethiopic word separator will also be familiar and comfortable with the  implicit hyphenation style.

With the Ethiopic word separator, a word can be wrapped at any internal point.  A hyphenation mark is not used because the word separator makes one unnecessary. Its hyphenation without a marker.

The word separator should not appear at the start of a line.  One letter and the separator at the start of a line is not ideal, I would recommend a thresh hold of at least 2 letters before the separator at the start of a line when a word is wrapped.

Ethiopic text without the Ethiopic word separator, should wrap one word at a time as stated.

**Comment by r12a** [comment]
@dyacob thanks for this.  

So, iiuc, 

1. when using wordspace it is common to wrap after any character, except that the wordspace mustn't start a new line, and it's better if there are actually 2 letters preceding it at line start.
2. when the wordspace is not being used (ie. when words are separated by spaces), the expectation is that whole words are wrapped.

I'll therefore add Ethiopic to the top left cell in the overview table, and move the existing Ethiopic name to the intersection of Wraps_characters/Other_word_separator.

I propose the following replacement text for the Ethiopic subsection (which needs to be moved to a lower section):

> Modern Ethiopic text may use spaces between words, in which case the expectation is that a whole word wraps to the next line as a unit. However, Ethiopic text may also use the traditional wordspace character (U+1361 ETHIOPIC WORDSPACE) to indicate word boundaries. When that is the case, Ethiopic wraps after any character, as long as the wordspace doesn't appear at the start of the line. (In fact, it is preferable to preceded the wordspace by at least two characters at the line start.)

What do you think?

(PS: We might need to look at the elreq doc, since what i wrote previously was what i concluded after reading that. It's also what the CLDR utility produced at https://unicode.org/cldr/utility/breaks.jsp)

**Comment by dyacob** [comment]
@r12a I think your replacement text is well stated.  The rule in (2) is valid for any punctuation symbol as well which might be worth mentioning.  So we then have two styles of word wrapping for Ethiopic which are driven by the presence or absence of the Ethiopic Wordspace:

- Modern Wrapping: Space is the separator - words break as a unit.
- Traditional Wrapping: Wordspace is the separator - words break after any character. Punctuation, including wordspace, may not appear at the start of the line. 

A caveat since line breaking and word wrapping get confused: A new line may begin with an "opening punctuation" such as a left parenthesis, left bracket or left quotation mark, etc.  In this case a line break may have occurred but _not_ a word wrap.

**Comment by r12a** [comment]
I posted a new version, relocating Ethiopic in the table (under Amharic), and rewriting the subsection at http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en#sec_ethiopic

Is that better?

**Comment by dyacob** [comment]
@r12a , yes.  I think this is a very clear way of presenting the information.  Good job!

**Comment by r12a** [comment]
thanks @dyacob .

**Comment by dyacob** [comment]
Realizing this issue is closed I thought I would still add this as a note of interest for possible future reference. The scribe here  ran out of line space and rather than start a new  line with the Ethiopic wordspace opted to right the symbol just below the last letter on the line.  Initially I thought it was a Rikrik but it is definitely a wordspace.  The scribe seems to have done this fairly often.  It helps demonstrate how "unbreakable" the wordspace was perceived to be:

(From http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_585_f166v)

![Screen Shot 2020-06-11 at 4 43 21 PM (2)](https://user-images.githubusercontent.com/8098333/84437370-dca60000-ac02-11ea-82ec-c0f3989a9f2b.png)
![Screen Shot 2020-06-11 at 4 33 20 PM (2)](https://user-images.githubusercontent.com/8098333/84437377-dfa0f080-ac02-11ea-80dd-0796acccf7a6.png)
