### ISSUE TITLE
[articles/typography/linebreak] Is it worth noting other downsides of manual entry ZWSP?

### ISSUE THREAD

**Issue by mcdurdin** [w3c/i18n-drafts#157]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

>It has been suggested that the Unicode character U+200B ZERO WIDTH SPACE could be useful to indicate word boundaries, but people writing these languages don’t use it.

Manual entry of ZWSP is not very practical because the user cannot see the separator in most scenarios. This leads to problems with ZWSP being inserted in the wrong position, or multiple times. Despite this, some standard keyboards such as Khmer NIDA still generate ZWSP with the Spacebar key. In fact, it has been suggested that word wrap algorithms ignore ZWSP for Khmer text because of data quality issues (sorry, I have been unable to locate where I saw this).

**Comment by r12a** [comment]
Thanks @mcdurdin.  I added some of this text to the article.
