### ISSUE TITLE
[articles/typography/linebreak]  Vietnamese uses syllable separators

### ISSUE THREAD

**Issue by NorbertLindenberg** [w3c/i18n-drafts#158]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

The table in the section Basic Parameters lists "Latin" as using spaces as word separators. I assume "Latin" here means the Latin script, not the Latin language. The Latin script is used for a large number of languages, including Vietnamese. Vietnamese uses spaces to separate syllables, which may or may not be complete words.

I suggest replacing "Latin" with a few sample languages that use the Latin script and use spaces as word separators, such as English or German, and listing Vietnamese separately in the syllable separator / wraps syllables cell.

**Comment by r12a** [comment]
@NorbertLindenberg i incorporated your suggestion to switch to language names, and included Vietnamese in a different location in the table.
