### ISSUE TITLE
[articles/ruby/index]  

### ISSUE THREAD

**Issue by dyacob** [w3c/i18n-drafts#16]
[source](http://w3c.github.io/i18n-drafts/articles/ruby/index.en) [en]

The explanation I found to be very clear in presenting the types of rubies and their distinctions.  I am wishing for a sentence or two to set the cultural context. Such as:
- When do they first appear in literature? In which language first?
- Are rubies taught in the school system? At what grade level?
- Are they found in all categories of literature, or just some? Which?

I assume the following are true since not stated otherwise. Perhaps add a note to clarify if any of these are not the case:
- Ruby text is never a non-letter symbol.
- Ruby text never appears over/beside non-letter symbols (avoided in groups).
- Phonetic ruby never modifies the _pronunciation_ of the text it annotates.
- Semantic ruby never changes the _meaning_ of the text it annotates (strictly a gloss)

**Comment by r12a** [comment]
We try to keep these articles short and to the point as references about how to do things or answering most frequently asked questions, and the purpose of this short article is mainly to establish some minimal background and some terminology for people wanting to know how to code HTML and CSS for ruby,  so i'm reluctant to expand the cultural dimension more. I could put in a link to the Wikipedia article in the Further Reading section.

>    Ruby text is never a non-letter symbol.
>    Ruby text never appears over/beside non-letter symbols (avoided in groups).

We place no restrictions on what you put in ruby text or how you use it, and i'm not sure others do either.

>    Phonetic ruby never modifies the pronunciation of the text it annotates.
>    Semantic ruby never changes the meaning of the text it annotates (strictly a gloss)

It's a slightly odd question: the ruby text indicates what the author wants you to pronounce the base text as or understand its meaning to be. I'm not aware of any rules about what they can or cannot put in the ruby text.  I guess mostly common sense prevails.

**Comment by dyacob** [comment]
Thanks for the explanation, closing.
