### ISSUE TITLE
[articles/typography/linebreak]  English-centric wording

### ISSUE THREAD

**Issue by NorbertLindenberg** [w3c/i18n-drafts#160]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

The article occasionally uses wording that seems to assume that the English way of handling text is normal and other ways are different or even weird. It should be written in a neutral way that assumes that all languages have equal standing.

– "By general agreement, the characters between spaces are normally agreed to be 'words'": Who has agreed to this? Do Arabs consider "الجامعات والكليات" two or three words? If three, then they would not agree to this "general agreement".

– "words in German may be a sequence of smaller words rammed together": the words are not "rammed together", but combined, sometimes with inflection, such as the "s" in "Verarbeitungsfunktion" indicating the genitive case.

– "However they do so, of course, in the opposite direction.": What's "opposite" here? Writing right to left is totally normal for these scripts.

– "Text in Arabic and Hebrew, however, gets significantly more complicated when it contains bidirectional text." As does text in any other language when it contains bidirectional text.

– "Korean Hangul is unusual..."

**Comment by r12a** [comment]
hi @NorbertLindenberg. Note first that the word 'word' is intentionally in scare quotes, and this section is about writing systems that use spaces to delimit 'words' (a list of examples is given).  The paragraph and following list is making that point that for these scripts applications consider space-delimited tokens as 'words', ie. the basic unit for wrapping text (if no hyphenation occurs). Your point about what does 'word' mean in Arabic is made in the 3rd bullet point.

> in the opposite direction

Added: "from, say, English".

> bidirectional text

-> Text in languages such as Arabic, Hebrew or Dhivehi, however... (it refers back to the previous para)

> Korean Hangul is unusual

it is!

**Comment by r12a** [comment]
See changes at https://github.com/w3c/i18n-drafts/commit/a47b74180dde4cc0ffea7d2bcbce87ab6525c2a0#diff-72d5160bdf2d502807cd2751e7057fab

**Comment by duerst** [comment]
The phrase 'rammed together' is still there. It really sounds weird, if not insulting ("why don't these Germans treat their words a bit more gently"). Also, the word "Kühlschrank" ("cooling closet") in German is considered as a word in and by itself, just as the English word "refrigerator". In addition, English does the same, although much less often, e.g. "camelcase" or "codespace" (from http://unicode.org/glossary/). So please replace 'rammed together' with something better.

**Comment by r12a** [comment]
Changed.

I also significantly rewrote the article, pulling the discussion of what is a word into a new section right up at the top.  If you have comments about that, please raise a new issue. Thanks.
