### ISSUE TITLE
[articles/typography/linebreak] Scripts, languages, and writing systems

### ISSUE THREAD

**Issue by NorbertLindenberg** [w3c/i18n-drafts#161]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

The article is sometimes not sufficiently clear whether it refers to a script, a language, or a writing system; at other times it limits itself too much to the main language written in a script. This matters because many scripts are used to write several languages, and many languages can be written in several scripts.

I recommend referring to the definitions of script and writing system in the Unicode glossary, and then being specific whenever using a name that might be ambiguous.
https://www.unicode.org/glossary/#script
https://www.unicode.org/glossary/#writing_system

Here are some cases where this matters:

– The table in the Basic Parameters section shows Balinese and Javanese in the cell "no word or syllable separator" / "wraps syllables". That's correct for traditional writing of the Balinese and Javanese languages in the Balinese and Javanese scripts, not always true for modern writing of the same writing systems, and incorrect for Balinese and Javanese language written in the Latin script, which is the most common nowadays.

– The Sundanese language today is more commonly written in Latin script than in Sundanese script; historically it has also been written in Javanese, Arabic, and other scripts. The rules described in "Sundanese, Cham: space as word separator" are for the Sundanese language written in Sundanese script and may not apply to the Sundanese language written in other scripts.

– The section on Thai, Lao, and Khmer refers to the languages and describes the problem (word-based line breaks without spaces) and the normal solution (dictionaries). However, it doesn't mention that the same problem also occurs with other languages written with the same scripts, but that a correct solution then needs to involve other dictionaries specific to those other languages rather than the dictionaries for the Thai, Lao, and Khmer languages. See
https://github.com/w3c/sealreq/issues/7

**Comment by r12a** [comment]
See changes at https://github.com/w3c/i18n-drafts/commit/a47b74180dde4cc0ffea7d2bcbce87ab6525c2a0#diff-72d5160bdf2d502807cd2751e7057fab
