### ISSUE TITLE
[articles/typography/linebreak]  order of scripts

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#162]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

In the table under “Basic parameters” the scripts are partly sorted alphabetically. “Hangul*” seems like been added later to the beginning; Georgian, Pau Cin Hau, Adlam, Deseret to the end. Shouldn’t the whole list be sorted alphabetically?

Also, “Sundanese, Eastern Cham” and “Balinese, Javanese, Batak, Western Cham” would need to be reordered.

**Comment by r12a** [comment]
Should be all fixed now, thanks.
