### ISSUE TITLE
[articles/typography/linebreak]  Approaches to line breaking

### ISSUE THREAD

**Issue by sbbic** [w3c/i18n-drafts#163]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

Just wanted to give a quick comment regarding this:

> In fact, it has been suggested that word wrap algorithms ignore ZWSP for Khmer text because of data quality issues.
http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en

I am not aware that this has been suggested for Khmer, and if such a suggestion was followed I think it would actually result in a degraded experience for users. A manually inserted ZWSP should be highly valued in comparison to any type of automatic word break. In fact, the new code for Khmer in ICU (that is waiting to be implemented) actually turns off the breakiterator if a ZWSP is detected to give preference to human input. This allows for a user who desires control, to control where breaks are placed (especially since in languages like Khmer there are different schools of thought as to whether compound words or certain word pairs should be allowed to be on different lines or kept together). Generally speaking, if a Khmer user places a ZWSP in a text, they do so because they want to control where line-breaks take place (like for book publishing). And if they don't place any ZWSP then they don't care as much where the line-breaks are placed, so long as the text breaks along a word boundary and not in the middle of a word.

**Comment by r12a** [comment]
Thanks for your comments. The sentence in question was taken from feedback at https://github.com/w3c/i18n-drafts/issues/157, but since it is unattributed i'm happy to rescind it.

I changed the text to read as follows:

> but recently major languages have line-breaking implementations at their disposal, which means ZWSP is not essential. Large-scale manual entry of ZWSP is also not very practical because the user cannot see the separator in most scenarios; this leads to problems with ZWSP being inserted in the wrong position, or multiple times. ZWSP may, however, be used to hand-craft and fix aspects of line-break behaviour.

Is that better?

(btw, off topic, are you aware of https://github.com/w3c/sealreq)

**Comment by r12a** [comment]
Hearing no objection to the changes, i am closing this issue. Reopen if there's more to be said on this topic.
