### ISSUE TITLE
[articles/typography/linebreak] Confusion between scripts and languages

### ISSUE THREAD

**Issue by dscorbett** [w3c/i18n-drafts#165]
[source](http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

The “Space delimited words” section says:
>They include those used for all European languages, including Cyrillic and Greek, all major Indian languages, such as Hindi, Bangla, Tamil, modern Semitic languages such as Arabic, Hebrew, and Syriac, and American languages such as Cherokee and Unified Canadian Syllabic (UCAS), etc.

This should be a list of either scripts or languages, not both. Cyrillic and Unified Canadian Syllabic are not languages. Hindi is not a script.

**Comment by r12a** [comment]
Thanks. Hindi was the odd man out. But i also restructured the sentence some.
