### ISSUE TITLE
[articles/typography/linebreak]  Ethiopic line breaks

### ISSUE THREAD

**Issue by duerst** [w3c/i18n-drafts#167]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en#sec_ethiopic) [en]

Two issues:
1) The fact that it is preferable to have two characters before a ":" word break on a new line is needlessly mentioned twice, once before and once after the figure.
2) The word 'archaic' feels somewhat inappropriate. It seems to imply that Ethiopic is an archaic script. Archaic often has a somewhat negative connotation ("way too old"). "ancient" may be better.

**Comment by r12a** [comment]
> The fact that it is preferable to have two characters before a ":" word break on a new line is needlessly mentioned twice, once before and once after the figure.

Hmm. Amazing what one fails to see when one is close to the text. Fixed.

> The word 'archaic' feels somewhat inappropriate. It seems to imply that Ethiopic is an archaic script. Archaic often has a somewhat negative connotation ("way too old"). "ancient" may be better.

I moved the text into a note and changed the wording slightly to avoid people assuming such  implications. See https://github.com/w3c/i18n-drafts/commit/1f22e67025a83ce243f85c36614fb2c6d7bc8ab2. I believe the word archaic, however, is correct, and better here than ancient. See the [definition of that word](https://www.thefreedictionary.com/archaic).  Note that an archaic script, or archaic features of a script, such as RTL text in Japanese, are not always ancient.
