### ISSUE TITLE
[quicktips/index]  Link to related info

### ISSUE THREAD

**Issue by shawna-slh** [w3c/i18n-drafts#173]
[source] (https://www.w3.org/International/quicktips/index.en) [en]

In this section:

> Navigation.  On each page include clearly visible navigation to localized pages or sites, using the target language.

Include a link to: https://www.w3.org/International/questions/qa-site-conneg

**Comment by r12a** [comment]
Thanks for the suggestion. Actually I realised (thank you) that most of the links for

> So, how do I do this?
>     HTML & CSS authors 

needed refreshing, so i did that (so far, English only).  If you click on that link at the bottom of the navigation section, it takes you to the Navigation section of our techniques index, and opens it up so you see:

> Getting started
> Linking to localized content
> Using content negotiation

Clicking on the last of these gives you a link to the article you mentioned (as well as other related information and articles).  I hope that does what you need (and perhaps a little more).

**Comment by shawna-slh** [comment]
cool
