### ISSUE TITLE
[qa-bidi-controls] named entities mismatch

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#174]
Section https://www.w3.org/International/questions/qa-bidi-controls#exceptions reads:

* U+200E:   LEFT-TO-RIGHT MARK (**\&rlm;**)
* U+200F:   RIGHT-TO-LEFT MARK (**\&lrm;**)

but should be

* U+200E:   LEFT-TO-RIGHT MARK (**\&lrm;**)
* U+200F:   RIGHT-TO-LEFT MARK (**\&rlm;**)

**Comment by r12a** [comment]
Fixed by https://github.com/w3c/i18n-drafts/pull/176
