### ISSUE TITLE
[questions/qa-headers-charset]  Link no longer works

### ISSUE THREAD

**Issue by meredevelopment** [w3c/i18n-drafts#178]
[source] (https://www.w3.org/International/questions/qa-headers-charset.en) [en]

Sadly Rex Swain's HTTP Viewer not longer functions, even though page is there. 

Rex writes: "10 December 2017: Due to abuse reported by the National Cybersecurity &
Communications Integration Center (NCCIC), my ISP has
disabled my HTTP Viewer. Thanks a lot, hackers! For a sample of what it used to do, click the Submit button"

**Comment by r12a** [comment]
The HTTP viewer seems to be working again now, so i'm closing this.
