### ISSUE TITLE
[questions/qa-forms-utf-8]  Translation request

### ISSUE THREAD

**Issue by claudia-ibidem** [w3c/i18n-drafts#187]
[source] (https://www.w3.org/International/questions/qa-forms-utf-8.es) [es]

Hi! 

We are Ibidem Group, a European translation agency. Our Internship Program includes college students who, in order to complete their studies, need to translate several texts under our supervision.
We always encourage them to select texts of a significant use for the community, and one of them suggested w3.org as a possible source for interesting texts to translate.
Would you allow us to translate some of your articles? 
We have a shortlist of W3.org articles that need translation to Spanish, French, German or Italian (the 4 languages we can deliver).  How do we do it?

Please let us know if you authorize this translation, so we can start working on it.
Thank you so much for your time and for the opportunity. If there is any other information you need, just let me know.

Best,
Claudia

**Comment by r12a** [comment]
Hello @claudia-ibidem.  Thanks for offering to translate some of the w3c internationalization articles. As long as we can receive quality-checked translations, this is certainly something we could do.

First step is to confirm that you agree with the instructions/requirements at https://www.w3.org/International/2004/06/translation.en.html.

Then please send a list of articles you'd like to translate to w3c-translators@w3.org and i'll send you back some information about how to proceed. (See for example https://lists.w3.org/Archives/Public/w3c-translators/2019AprJun/0028.html.)

**Comment by r12a** [comment]
This was followed up.
