### ISSUE TITLE
[questions/qa-html-language-declarations]  Armenian language?

### ISSUE THREAD

**Issue by makhyan** [w3c/i18n-drafts#188]
[source] (https://www.w3.org/International/questions/qa-html-language-declarations) [en]

I was reviewing the lang parameters and noticed that W3.org is referencing [IANA Language Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) which is incorrectly categorizing Armenia language. Its common practice to have hy used for Armenian and not hyx

%%
Type: language
Subtag: hya
Description: Hya
Added: 2009-07-29
%%
Type: language
Subtag: hyw
Description: Western Armenian
Added: 2018-03-08
Comments: see also hy
%%
Type: language
Subtag: hyx
Description: Armenian (family)
Added: 2009-07-29
Scope: collection
%%

**Comment by aphillips** [comment]
That's not quite a correct reading of the registry and BCP47. The registry has:

```
%%
Type: language
Subtag: hy
Description: Armenian
Added: 2005-10-16
Suppress-Script: Armn
Comments: see also hyw
%%
```

The subtag `hyx` is a collection code. Collection codes are not recommended for use in making language tags. See [BCP47, Section 4.1](https://tools.ietf.org/html/bcp47#section-4.1), which says in part:

```
 4.  Use subtags or sequences of subtags for individual languages in
       preference to subtags for language collections.  A "language
       collection" is a group of languages that are descended from a
       common ancestor, are spoken in the same geographical area, or are
       otherwise related.  Certain language collections are assigned
       codes by [ISO639-5] (and some of these [ISO639-5] codes are also
       defined as collections in [ISO639-2]).  These codes are included
       as primary language subtags in the registry.  Subtags for a
       language collection in the registry have a 'Scope' field with a
       value of 'collection'.  A subtag for a language collection is 
       always preferred to less specific alternatives such as 'mul' and
       'und' (see below), and a subtag representing a language
       collection MAY be used when more specific language information is
       not available.  However, most users and implementations do not
       know there is a relationship between the collection and its
       individual languages.  In addition, the relationship between the
       individual languages in the collection is not well defined; in
       particular, the languages are usually not mutually intelligible.
       Since the subtags are different, a request for the collection
       will typically only produce items tagged with the collection's
       subtag, not items tagged with subtags for the individual
       languages contained in the collection.
```

If you have concerns about the reference in the record for `hy` to the `hyw` subtag, you should suggest changes to the IETF language subtag registry list at `ietf-languages@ietf.org`. Thanks!
