### ISSUE TITLE
[questions/site-conneg]  Make URIs consistent

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#19]
[source](https://w3c.github.io/i18n-drafts/questions/qa-site-conneg.en) [en]

_“…hard-wired to a particular language version, such as `qa-site-conneg.en.html`. […] The only time you would use `qa-site-conneg.en` is when…”_

Once with suffix `.html`, the other time without. It should be the same both times, I think. (My preference would be `qa-site-conneg.en` without suffix `.html`.)

**Comment by r12a** [comment]
yes, i pulled this section back from a general comment about content negotiation to one about language negotiation, but looking at it again, i think it makes more sense to widen it back out. Here is my replacement:

"Using content negotiation also makes it a lot easier to manage translations and to pass links to others.

"Without content negotiation, the source text of a page would be full of links hard-wired to a particular language version, such as qa-site-conneg.en.html or qa-site-conneg.html.en. With content negotiation, that link becomes simply qa-site-conneg.

"That reduces ...

"You may still use something like qa-site-conneg.en, but only when you specifically want to point to the English language version.
