### ISSUE TITLE
[translator-ru]  Error in the translation of the article

### ISSUE THREAD

**Issue by Scarsgard-S** [w3c/i18n-drafts#191]
[source] (https://www.w3.org/International/questions/qa-lang-why.ru#survey) [ru]
In the Russian translation of the article there is a mistake in the paragraph "Parser and scripts" in the fourth paragraph of the list in the word "apply": 
"...приминення такого культурного специфического стайлинга, как соответствующие..."
There is a mistake in the word 'приминення'.
![1](https://user-images.githubusercontent.com/50478395/57510186-c8f8dd80-730e-11e9-9795-eeaae2d7beb5.png)

**Comment by r12a** [comment]
Thanks for reporting. My guess is that that word should be применение ?

**Comment by Scarsgard-S** [comment]
Sorry for the long wait for my reply. Yes, you wrote correctly.

**Comment by r12a** [comment]
Fixed by https://github.com/w3c/i18n-drafts/commit/591b58a25c32a62a4dc61fca8e2b6ec097d54404
