### ISSUE TITLE
[questions/site-conneg]  Arabic script

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#20]
[source](https://w3c.github.io/i18n-drafts/questions/qa-site-conneg.en) [en]

_“If you were English and faced with a Persian page, and if the link to the English page was written in Arabic, you might not find it easily!”_

You might want to add ‘script’ in order to prevent confusion with Arabic language:

If you were English and faced with a Persian page, and if the link to the English page was written in Arabic **script**, you might not find it easily!

**Comment by r12a** [comment]
change made. Thanks.
