### ISSUE TITLE
https://www.w3.org/International/articlelist/ doesn't seem to work

### ISSUE THREAD

**Issue by brandelune** [w3c/i18n-drafts#204]
I've tried to open it with Safari/Safari Technology Preview/Firefox/Firefox Developer Edition/Vivaldi/Opera and none produced more than this page, without any link working.

<img width="537" alt="Screen Shot 2019-07-21 at 22 35 53" src="https://user-images.githubusercontent.com/28946328/61591982-04196600-ac08-11e9-9087-352a8c0bbb26.png">

**Comment by himorin** [comment]
@r12a not sure why (and how things are working), but any URL under articlelist/ returns the same html file (as index.html) even for invalid (or, say random string) URL...

**Comment by brandelune** [comment]
The underlying javascript seems to not work.

**Comment by r12a** [comment]
Remove the / at the end.  

What caused the / to appear there? Is it a link somewhere that needs to be fixed?

**Comment by brandelune** [comment]
Indeed. The / appears in that page:
https://www.w3.org/International/2004/06/translation

"Finding a page that needs translation
To find articles that need translation, go to the **list of articles** and in the top right of the page click on the language you are interested in."

**Comment by r12a** [comment]
Ok, that should now be fixed.

Thanks for reporting it.

**Comment by brandelune** [comment]
Fixed indeed.
