### ISSUE TITLE
https://www.w3.org/International/articlelist is only partially translated

### ISSUE THREAD

**Issue by brandelune** [w3c/i18n-drafts#205]
Some languages have all the strings translated, some not, Spanish has an extra paragraph where it says "contact us to translate this page", etc...

I'm not seeing this page on github. It is hosted somewhere else ? I'd like to provide the remaining French strings.

**Comment by r12a** [comment]
It is only on the W3C server.  I'll send you a copy for translation.

**Comment by brandelune** [comment]
Thank you. I'll close this issue when I send you the translation.

**Comment by r12a** [comment]
@brandelune there are only 2 items needing translation.  It will be easiest, i think to just provide them here, and have you provide the translations below. I'll then copy into place, and add you as the translator and we're done. 

```
<p>If a title in the list below is in English, the article is not available in the language of this page. The list of articles was last updated on <span id="lastestTitles"></span>.</p>
```

```
<meta name="description" content="A list of articles, tutorials and guidelines from the W3C Internationalization Activity." />
```

---
btw, I rewrote the structure and styling of the page at https://www.w3.org/International/articlelist.fr (something i've been wanting to do for a while now) while preparing for your translation.

**Comment by brandelune** [comment]
<p>Si un titre dans la liste ci-dessous apparaît en anglais, l'article n'est pas disponible en français. La liste a été mise à jour le <span id="lastestTitles"></span>.</p>
<meta name="description" content="Une liste d'article, de tutoriels et de guides offerts par l'Activité internationalisation du W3C." />

1) their is a bug in the English page. Check:
https://www.w3.org/International/articlelist
then click on a language and then on English in the language selection block. You'll end up here:
https://www.w3.org/International/articlelist.en

2) The English page should not have the above string since all the titles are in English and the language of the page is English...

3) The proper string to send the translators should rather be:
→ If a title in the list below is in English, the article is not available in [put the language of the page here].

or something like this...

4) make sure that the date in <span id="lastestTitles"></span> is properly displayed according to the selected language.

**Comment by r12a** [comment]
> their is a bug in the English page. Check:
> https://www.w3.org/International/articlelist
> then click on a language and then on English in the language selection block. You'll end up here:
> https://www.w3.org/International/articlelist.en

It's actually the same page if you're browser preferences are set to english. Redirection is done by a .var file.  If you go to https://www.w3.org/International/articlelist and your browser preferences are set to, say, French, you should end up at https://www.w3.org/International/articlelist.fr.  But if you click on 'English' you need to go to the English page, therefore the .en.  Does that clarify?

> The English page should not have the above string since all the titles are in English and the language of the page is English...

Good point. Should be fixed now.

> The proper string to send the translators should rather be:
> → If a title in the list below is in English, the article is not available in [put the language of the page here].

We could do that, yes.  I see you already did it in the translation.

>   make sure that the date in is properly displayed according to the selected language.

We used iso 8061 format to be language-neutral, so your translation looks like this:

> Si un titre dans la liste ci-dessous apparaît en anglais, l'article n'est pas disponible en français. La liste a été mise à jour le 2019-07-22.

Is the 'le' appropriate in this case ?

**Comment by brandelune** [comment]
> It's actually the same page if you're browser preferences are set to english. Redirection is done by a .var file. If you go to https://www.w3.org/International/articlelist and your browser preferences are set to, say, French, you should end up at https://www.w3.org/International/articlelist.fr. But if you click on 'English' you need to go to the English page, therefore the .en. Does that clarify?

Well, yes, but if you check the page ending in .en you'll see that the display is different from the English page that does not end in .en.

> > Si un titre dans la liste ci-dessous apparaît en anglais, l'article n'est pas disponible en français. La liste a été mise à jour le 2019-07-22.

> Is the 'le' appropriate in this case ?

No. The French should rather be: "Date de la mise à jour : 2019-07-22." but the very best would be to have the date displayed as 22-07-2019.

**Comment by r12a** [comment]
> Well, yes, but if you check the page ending in .en you'll see that the display is different from the English page that does not end in .en.

Try refreshing your cache.  It should be the same, but i just changed it, so your browser may be over-caching.

> No. The French should rather be: "Date de la mise à jour : 2019-07-22." but the very best would be to have the date displayed as 22-07-2019.

After some thought, i figured that it's not necessary to separate the update of the list from the update of the page, especially given that the page has very little to it other than the list of titles.  There's a 'Last changed' line at the very bottom of the page, which means i can just deleted the problematic sentence. It took a while to figure out how to get the right date in there, but i managed it.  You can see it at the bottom of the French page - i'll need to propagate the changes through all the other translated pages.  (That's another thing i've been wanting to do for a while.)

**Comment by brandelune** [comment]
Thank you, it looks like the issue is solved now.

> There's a 'Last changed' line at the very bottom of the page, which means i can just deleted the problematic sentence. It took a while to figure out how to get the right date in there, but i managed it. You can see it at the bottom of the French page - i'll need to propagate the changes through all the other translated pages. (That's another thing i've been wanting to do for a while.)

The last 2 lines of the page in that part is not meant to be localized ?

**Comment by r12a** [comment]
> The last 2 lines of the page in that part is not meant to be localized ?

Copyright line, no. Last changed line, yes.  I did the latter already.
