### ISSUE TITLE
[questions/site-conneg]  MultiViews in camel case

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#21]
[source](https://w3c.github.io/i18n-drafts/questions/qa-site-conneg.en) [en]

_“**multiviews** or **type maps**”_

Usually spelled in camel case: **MultiViews**. Maybe even in monospace font as `localStorage` above.

This applies also to the link title _how to use multiviews_.

**Comment by r12a** [comment]
Change to camelCase made, but not monospace as not used as a keyword in this case.
