### ISSUE TITLE
French translation of  "Character encodings: Essential concepts"

### ISSUE THREAD

**Issue by brandelune** [w3c/i18n-drafts#216]

**Comment by r12a** [comment]
Should be fine, if you mean this https://www.w3.org/International/articles/vertical-text/

The article hasn't been updated for a while, but i don't think anything has changed in the interim.

**Comment by brandelune** [comment]
Thinking about that, I'd rather cancel this and work in the order displayed in International/articlelist. Which means I'll be working on "[Character encodings: Essential concepts](https://www.w3.org/International/articles/definitions-characters/index)"

**Comment by r12a** [comment]
Ok. I just made some time to prep the essential concepts doc for translation. Be sure to take the latest version from github, and go ahead. Thanks.

**Comment by r12a** [comment]
Oh, just a sec... I need to update a couple of urls.

**Comment by r12a** [comment]
Ok, ready now.

**Comment by brandelune** [comment]
There are a number of strings inconveniently put into images in that article.

for ex:
1) https://www.w3.org/International/articles/definitions-characters/index-data/unicodeplanes.png
2) https://www.w3.org/International/articles/definitions-characters/index-data/encodings-utf8.png
3) https://www.w3.org/International/articles/definitions-characters/index-data/encodings.png

1) needs some work to be converted to HTML+CSS
2) and 3) don't really need the "Character Encoding" / "Character Encodings" strings *inside* the image. The image could be converted to a table with the same contents.

Here is an (ugly) attempt at fixing 2) and 3):

'''
<html>
    <head>
	<style>
	 body {
	     font-family: monospace;
	 }
	 td {
	     text-align: center;
	 }
	 .big_tifinagh {
	     font-size: 3em;
	 }
	 .small_unicode {
	     
	 }
	 .arrows {
	     font-size: 3em;
	     color: orange;
	 }
	 .small_tifinagh {
	     color: orange;
	 }
	 .utf8 td {
	     font-size: 1.5em;
	     border: solid orange 1px;
	 }
	 #encoding_name, #process {
	     color: brown;
	     border: solid blue 1px;

	 }
	</style>
    </head>
    <body>
	<img src="https://www.w3.org/International/articles/definitions-characters/index-data/encodings-utf8.png" />
	<table border="0">
	    <tr class="big_tifinagh"><td></td><td>ⴰ</td><td>ⵣ</td><td>ⵓ</td><td>ⵍ</td><td>!</td></tr>
	    <tr class="small_unicode"><td></td><td>2D 30</td><td>2D 63</td><td>2D 53</td><td>2D 4D</td><td>21</td></tr>
	    <tr class="arrows"><td></td><td>↓</td><td>↓</td><td>↓</td><td>↓</td><td>↓</td><td id="process">◁ Character<br/>encoding</td></tr>
	    <tr class="small_tifinagh"><td></td><td>ⴰ</td><td>ⵣ</td><td>ⵓ</td><td>ⵍ</td><td>!</td></tr>
	    <tr class="utf8"><td id="encoding_name">UTF-8 ▷︎</td><td>E2 B4 B0</td><td>E2 B5 A3</td><td>E2 B5 93</td><td>E2 B5 8D</td><td>21</td></tr>
	</table>
    </body>
</html>
'''

**Comment by r12a** [comment]
Hmm. Unfortunately, there are lot's of dragons in your code, i'm afraid.  But you're right about the problem of translatable text in graphics.  Let me give it some thought.  Ideally we'd code it in SVG, but i'm not sure i have time for that.

**Comment by r12a** [comment]
@brandelune i just committed a new version of the page where i replaced one of the images with an SVG.  Could you take a look and let me know whether you think that will solve the problem?

**Comment by brandelune** [comment]
SVG is perfect, and yes, dragons :) I'll check all that out shortly.

**Comment by r12a** [comment]
Ok, then i'll try to find a moment later on to convert the other diagram to SVG also.

**Comment by brandelune** [comment]
I just sent a PR for the article.

**Comment by r12a** [comment]
The article is now live, and includes additional SVG replacements for graphics (with translations provided). So i'll close this. Reopen if you have an issue.
