### ISSUE TITLE
[articles/linebreak]  Usage of kanji character of "圖"

### ISSUE THREAD

**Issue by kazuhito-kidachi** [w3c/i18n-drafts#219]
[source] (https://w3c.github.io/i18n-drafts/questions/qa-reference-links.en) [en]
From a native Japanese viewpoint, it seems that the kanji character of "図" is more suitable and more natural rather than "圖" for the document.

Thanks!

**Comment by r12a** [comment]
Thanks!  Bug fixed! https://github.com/w3c/i18n-drafts/commit/b28795f8b3319e388cd2e09d943ee128ed6aaf19
