### ISSUE TITLE
[questions/site-conneg]  Note that localStorage requires JavaScript?

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#22]
[source](https://w3c.github.io/i18n-drafts/questions/qa-site-conneg.en) [en]

_“You can do the same thing with `localStorage`, if you prefer that to cookies.”_

It might be worth noting that `localStorage` requires JavaScript in order to work, while cookies work without such dependency.

**Comment by r12a** [comment]
Well actually you may use JavaScript, PHP or other things, such as Apache directives to work with cookies, too, so i'm happy to not get into detail about localStorage.
