### ISSUE TITLE
[articles/definitions-characters/index]  Duplicate graphic for UTF-8, none for UTF-16 and 1 for UTF-32

### ISSUE THREAD

**Issue by crysaro** [w3c/i18n-drafts#222]
[source] (https://www.w3.org/International/articles/definitions-characters/) [en]

In this section, CHARACTER SETS, CODED CHARACTER SETS, AND ENCODINGS, [https://www.w3.org/International/articles/definitions-characters/#charsets], the second image shows a 2 identical graphics for UTF-8, none for UTF-16 and 1 for UTF-32. The last sentence before those image was "The encoding forms that can be used with Unicode are called UTF-8, UTF-16, and UTF-32.".

**Comment by r12a** [comment]
Thanks for the report.  Should be fixed now.
