### ISSUE TITLE
[questions/qa-lang-priorities]  Edge/Chrome typo

### ISSUE THREAD

**Issue by irenetang1993** [w3c/i18n-drafts#225]
[source] (https://www.w3.org/International/questions/qa-lang-priorities#specifying) [en]

> If you choose a language+region combination, Chrome will set that option followed by just the vanilla language. For example, if you choose French (Canada), **_Edge_** will add that followed by French in your on-screen preference list.

'Edge' is supposed to be 'Chrome', am i right ?

**Comment by r12a** [comment]
Thanks for the report.

Of course, we may soon need to change this again because Edge will be based on the Blink engine.
