### ISSUE TITLE
[articles/article-text-size]  Further Reading links are broken or hostile.

### ISSUE THREAD

**Issue by Cthulahoop** [w3c/i18n-drafts#228]
[source] (https://www.w3.org/International/articles/article-text-size.en) [en]

In the "Further Reading" section, the top two links are not working as expected:

- The link to IBM's "Guidelines to design global solutions" points to a site that has been taken down (this is also true for the link shown in the "ENGLISH AND CHINESE ARE PARTICULARLY PROBLEMATIC" section).
- The link to "Graphic text & translation problems" goes to a series of pages that request users to allow notifications and appear to be suspicious or hostile.

**Comment by r12a** [comment]
Thanks for reporting this!  I removed the links to the IBM page, and pointed to a new location for the other.  I also made these changes for the 12 translated versions of the page.
