### ISSUE TITLE
[questions/site-conneg]  example .var file

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#23]
[source](https://w3c.github.io/i18n-drafts/questions/qa-site-conneg.en) [en]

_“Here is an example of a `.var` file:”_

It might be worth noting that this is an example ot the `qa-lang-priorities.var` file.

**Comment by r12a** [comment]
Since that example actually doesn't represent the qa-lang-priorities.var file, i genericised the names (to my-article). Thanks for reminding me to do that.  I did however change the introduction to say that it's an example of the my-article.var file.
