### ISSUE TITLE
HTML Translate Attribute with Expression Engine 3.5.10

### ISSUE THREAD

**Issue by Beaton1979** [w3c/i18n-drafts#230]
Does HTML Translate Attribute work with Expression Engine 3.5.10? What do I need to achieve this?

**Comment by r12a** [comment]
Not sure. Maybe the best approach is to try it out. There are some tests at https://www.w3.org/International/tests/#html5-translate which may or may not be useful.

**Comment by r12a** [comment]
Seems stale.
