### ISSUE TITLE
dir=<rtl/auto> for placeholder in input field

### ISSUE THREAD

**Issue by Elia-Sh** [w3c/i18n-drafts#232]
After reviewing: 
https://www.w3.org/International/questions/qa-html-dir
and understanding that I need to open a queestion on github about - 
https://github.com/w3c/i18n-drafts/blob/gh-pages/questions/qa-html-dir.en.html

After trying to apply `dir="auto"` I've noticed that the placeholder stays aligned "LTR",
the placeholder is written in Hebrew and the input form reactes to the attribute `dir="auto"`,
meaning the value of the text field is aligned properly - based on the language that is used,
but the placeholder remains,
example:
![gif of placeholder](https://i.ibb.co/wL22G8J/placeholder-rtl.gif)

```
<input type="text" class="form-control" id="inlineFormInputGroup" placeholder="מייל" dir="auto">
```

The above was tested both in chrome and firefox, and the behaviour is identical.

Is there an option to discuss the affect of dir="auto" on the placeholder of an input field,
or at least improve the documentation - https://www.w3.org/International/questions/qa-html-dir
to mention this issue?

Thanks,
Elia.

**Comment by r12a** [comment]
An issue was raised in the HTML spec development repository related to this topic.  It has, however, gone quiet. See https://github.com/whatwg/html/issues/4903 

I'll close this issue in favour of that one, in the hope that some clarity emerges soon which can then be reflected in the article.
