### ISSUE TITLE
[questions/qa-personal-names]  The order of Russian names is slightly wrong

### ISSUE THREAD

**Issue by AlinaMalinaA** [w3c/i18n-drafts#236]
[source] (https://www.w3.org/International/questions/qa-personal-names) [en]

Modern Russian people prefer another than given in article order of names: 
familyName-givenName-patronymic.

More comfort way to display the full Russian name is:
Абрамова Алина Алексадровна (Abramova Alina Aleksandrovna) 
rather than
Алина Александровна Абрамова.

**Comment by xfq** [comment]
Related: https://russian.stackexchange.com/questions/11598/what-order-are-the-parts-of-a-full-russian-name-in

**Comment by r12a** [comment]
@AlinaMalinaA thanks for the comment!  I made a change to the article, which you can see at https://github.com/w3c/i18n-drafts/pull/257/files
