### ISSUE TITLE
[questions/qa-html-language-declarations]  example of the lang declaration

### ISSUE THREAD

**Issue by vmukhachev** [w3c/i18n-drafts#237]
[source] (https://www.w3.org/International/questions/qa-html-language-declarations) [en]

The webpage recommends to use the next markup when "title" attribute contains a text in page lang, while the content of the link in different lang:
```html
<span title="Spanish"><a lang="es" href="qa-html-language-declarations.es">Español</a></span>
```

Why not to recommend to use the next markup:
```html
<a title="Spanish" href="qa-html-language-declarations.es" hreflang="es"><span lang="es">Español</span></a>
```
?
In the later case the `title` is placed on the interactive element, which could work better. At least, Chrome's browser's developer tools show it as a "description" of the link.

**Comment by r12a** [comment]
That seems reasonable to me.  I changed the example in the proposed [update of that article](https://w3c.github.io/i18n-drafts/questions/qa-html-language-declarations).

Reopen if there are more points to make on this topic.

**Comment by vmukhachev** [comment]
@r12a thanks!
