### ISSUE TITLE
github tutorial location

### ISSUE THREAD

**Issue by brandelune** [w3c/i18n-drafts#239]
The github tutorial here:
https://w3c.github.io/i18n-activity/guidelines/github

Should be linked to in the Translation page, where Github is referred to:
https://www.w3.org/International/2004/06/translation
(Getting the source text... If you are familiar with Github...)

I could not find the contents of that page here so I'm creating an issue instead.

**Comment by r12a** [comment]
Thanks @brandelune.  I added a link to the document.
