### ISSUE TITLE
[questions/qa-chars-vs-markup]  missing dates in footer

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#24]
[source](https://www.w3.org/International/questions/qa-chars-vs-markup.pl) [pl]

The footer reeds _“Angielska wersja dokumentu z dnia **$enVersion**. Tłumaczenie wykonano dnia **$thisVersionPlain** GMT”_ instead of the dates. This applies only to the Polish translation.

**Comment by r12a** [comment]
well spotted. Fixed by https://github.com/w3c/i18n-drafts/commit/5784d435bf97405e9479d6c1969939d2e4ce2c09
