### ISSUE TITLE
language script region code

### ISSUE THREAD

**Issue by datapod** [w3c/i18n-drafts#240]
[source] (https://www.w3.org/International/questions/qa-choosing-language-tags) [en]

https://www.w3.org/International/questions/qa-choosing-language-tags, in the section:
 
Check the context and ordering for variant subtags.
.....
eg. zh-Latn-TW-pinyin.

It is unusual to see pinyin for Chinese scripts in Taiwan. One would see more often the Wage-Giles or localized transliterations than pinyin. Is it possible to provide examples applying non-pinyin for zh-Latn-TW-****?

Thank you,
--Jackie

**Comment by r12a** [comment]
Good point.  I changed the example to zh-Latn-CN-pinyin – not something you're likely to want to use, but at least more coherent.

(Change made for all translations, too.)
