### ISSUE TITLE
[articles/article-text-size] Reformulate or remove Comment for using encodings for soft line breaks for German compounds

### ISSUE THREAD

**Issue by sisyphosloughs** [w3c/i18n-drafts#241]
[source] (https://www.w3.org/International/articles/article-text-size.de) [de]
The article is very good. From my point of view the comment from the translator needs discussion and should maybe removed. My experience with translators is, that most of them are not technically scilled enought to deal with encodings for soft linke breaks. This approach should be absolute exceptional. The way how it is written suggests using of encodings for soft line breaks in general.

**Comment by r12a** [comment]
Thanks for the report.

I think that use of `&shy;` avoids complexities related to encoding, however, I would agree that soft-hyphens should only be used on an exceptional basis, and i'd also agree that some additional explanations would be useful here (such as what &shy; represents, and that by using &shy; you disable other possible breakpoints for the text).

cc @gunnarbittersmann 

I'll leave this issue open, while we consider alternatives.  We may need to augment the article itself, or point to a new article that discusses hyphenation.

**Comment by r12a** [comment]
In the absence of comment from the translator, i'll close this and comment out the translator's note.
