### ISSUE TITLE
[questions/qa-b-and-i-tags]  Link doesn't work

### ISSUE THREAD

**Issue by anastasia-zdv** [w3c/i18n-drafts#242]
[source] (https://www.w3.org/International/questions/qa-b-and-i-tags.de) [de]

This link does not work: 4.5 Text-level semantics

**Comment by xfq** [comment]
Thanks for your report!

The editor's draft has been updated, and https://www.w3.org/International/questions/qa-b-and-i-tags.de will be updated soon.

**Comment by r12a** [comment]
> https://www.w3.org/International/questions/qa-b-and-i-tags.de will be updated soon.

Done. Thanks both.
