### ISSUE TITLE
[questions/qa-i18n.ru] Found some typos 

### ISSUE THREAD

**Issue by corocoto** [w3c/i18n-drafts#246]
[source] (https://www.w3.org/International/questions/qa-i18n.ru#survey) [ru]

I found some typos in this article.
Like:
* Extra quotes:
> Интернационализация часто пишется как " "i18n", где 18 - это число букв между 'i' and 'n' в английском варианте слова "internationalization".
* Incorrect phrases (Necessary to make phrases in an another form. Because it sounds unusual now):
>Интернационализация - это создание и развитие содержания продукта, программы или документации, чтобы позволить лёгкую локализацию для целевых рынков, различающихся по культуре, региону или языку.

>Создание и разработка таким образом, чтобы не было преград при локализации и международном применении.

**Comment by r12a** [comment]
> Extra quotes

Should be fixed now. Thanks.

> Incorrect phrases

If you'd like to provide the better translation here, i'll move it into the document.  Thanks.

**Comment by corocoto** [comment]
@r12a Yes, I'll trying to change this context so that it sounds better.

**Comment by r12a** [comment]
Fixed by the commit above.
