### ISSUE TITLE
[questions/qa-bidi-controls]  Switch lrm/rlm (editorial)

### ISSUE THREAD

**Issue by donoliverio** [w3c/i18n-drafts#247]
[source] (https://www.w3.org/International/questions/qa-bidi-controls) [en]

I think the documentation is wrong in the entities mentioned, it says

    U+200E:   LEFT-TO-RIGHT MARK (&rlm;)

I think is not (& rlm;) It must be (& lrm;)

**Comment by xfq** [comment]
Thanks for your report! Looks like it's reversed. (See https://www.w3.org/TR/WCAG20-TECHS/H34.html#H34-description for example.)

I'll submit a PR to fix it.

**Comment by xfq** [comment]
It seems to have been fixed in https://github.com/w3c/i18n-drafts/commit/6db4a980b0bc0869caa7b0436c4ea12a2b8872a2

@r12a would you please update the version in www.org/International/ as well?

**Comment by r12a** [comment]
Ok. Should be fixed. Thanks for the report.
