### ISSUE TITLE
[questions/qa-escapes]  Various things in ‘Use in XHTML’ section

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/i18n-drafts#25]
[source](https://www.w3.org/International/questions/qa-escapes.en) [en]

```
`<p><strong class="leadin" id="useinxhtml">Use in XHTML.</strong>`
```

The following section is rather about XML than XHTML. Shouldn’t the heading reflect this? Maybe “Use in XML / XHTML”?

```
`<p>If you use <a class="print" href="http://www.w3.org/TR/html401/sgml/entities.html">HTML-defined character entity references </a> (such as <span class="kw">&amp;aacute;</span>)`
```

The link refers to the HTML 4 spec. Maybe better link to HTML5 https://www.w3.org/TR/html5/syntax.html#named-character-references?

Here it still says “character entity references”. Should be changed to HTML5 speak “named character references” as otherwise in the article.

`<span class="kw">&amp;aacute;</span>` should be marked up as `<code>&amp;aacute;</code>`.

**Comment by r12a** [comment]
the section 'Use in XHTML' is very much about XHTML, actually, since the point is that the named character references that can be used in XHTML don't work in XML, so you need to be careful when using XHTML.

i'll fix the other points, thanks.
