### ISSUE TITLE
arlo cameras at my home were erased on 10-03-2017 without my permission

### ISSUE THREAD

**Issue by southside** [w3c/i18n-drafts#250]
check to see if it can be recovered and who erased it has my other gmail being used mrandmrs.coy2018@gmail.com

**Comment by southside** [comment]
can you help me retrieve this informative

**Comment by southside** [comment]
can you help me re open this subject?

**Comment by swickr** [comment]
@southside [W3C](https://www.w3.org) has nothing at all to do with Arlo's products.  We cannot help you with this.  GitHub issues of this sort here in W3C's repositories are not appropriate; that is why the subject has been closed in GitHub.
