### ISSUE TITLE
[questions/qa-personal-names] Honorific for women in Spanish

### ISSUE THREAD

**Issue by juanruitina** [w3c/i18n-drafts#253]
[source] (https://www.w3.org/International/questions/qa-personal-names) [en]

Similar to "Mademoiselle" vs "Madame", the use of "Señorita" in Spanish is discouraged by [inclusive language guides](http://www.inmujer.gob.es/servRecursos/formacion/GuiasLengNoSexista/docs/Guiaslenguajenosexista_.pdf), as it is considered to have a sexist connotation. The argument is that women deserve to be treated with equal respect regardless of their marital status, as is the case with men. ["Nueva Gramática"](http://aplica.rae.es/grweb/cgi-bin/z.cgi?t=5237775104261005506957712&s=1&ap=16.16h) by the Real Academia Española, that normalises the (Spain) Spanish language, also mentions this concern.

So I suggest that "Señorita Carreño" is addressed as "Señora Carreño" instead :)

**Comment by r12a** [comment]
hola @juanruitina Thanks for your comment.  I added something along those lines to the PR at https://github.com/w3c/i18n-drafts/pull/257/files.   I didn't just swap out Señorita for Señora because that gave me an introduction to the point you made.  If you have further comments, just reopen this or comment on the PR. Gracias.

**Comment by juanruitina** [comment]
That's great! Thanks for making those changes. One comment though: "Doña" isn't a good alternative, as Don/Doña is only used [with given names, not with surnames](https://en.wikipedia.org/wiki/Don_(honorific)name) (She would be Doña María José or Señora Carreño).

**Comment by r12a** [comment]
> (She would be Doña María José or Señora Carreño).

Indeed.  I think my brain must have been running on empty.  I removed 'or Doña'. Thanks.
