### ISSUE TITLE
[questions/qa-personal-names]  Additional translation needed

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-drafts#261]
[source](https://w3c.github.io/i18n-drafts/questions/qa-personal-names.en)

@gunnarbittersmann @cmatmar1 @notabene @arkhi 

Additions have been made to the text of [this article](https://w3c.github.io/i18n-drafts/questions/qa-personal-names.en), and copied (in english) to it's translations.  Could you please let me know whether you can provide updated translations?

thanks.

**Comment by arkhi** [comment]
@r12a: I will have a look at the French translation tonight or tomorrow.

**Comment by notabene** [comment]
Hah! Fabien was faster than me! 😁

**Comment by arkhi** [comment]
@goulvench: Since we’re tweaking URL for collaborators, I wonder if you’d like to add yours.

**Comment by goulvench** [comment]
@arkhi You can link my name to my personal website, https://userland.fr/. Thanks for the heads-up!
