### ISSUE TITLE
Xiānshēng & Xiānsheng

### ISSUE THREAD

**Issue by arkhi** [w3c/i18n-drafts#264]
I hope someone more knowledgeable than me about the topic can help with this detail on https://www.w3.org/International/questions/qa-personal-names.en.

In Simplified Chinese and Hanyu Pinyin, although transliteration of 先 is Xiān and 生 is Shēng, I see (and I feel like I heard) 先生 is Xiānsheng instead of Xiānshēng.

I can’t find any authoritative resource about this, but I’d be happy to learn something.

**Comment by xfq** [comment]
I'm not an expert, but I think the rule of [neutral tone](https://w3c.github.io/clreq/#term.neutral-tone) / [tone sandhi](https://en.wikipedia.org/wiki/Standard_Chinese_phonology#Tone_sandhi) is inconclusive, so the transcription should probably not be changed because of it.

**Comment by xfq** [comment]
I asked a Chinese teacher and she said that 先生 is Xiānsheng in almost all Chinese textbooks, and what she teaches is also neutral tone.
