### ISSUE TITLE
[questions/qa-ruby]  Ruby text source

### ISSUE THREAD

**Issue by ihateliquorice** [w3c/i18n-drafts#269]
[source] (https://www.w3.org/International/questions/qa-ruby) [en]

I am wondering where the information for ruby text is stored. Specifically, when using Word, I wish to know where the phonetic guide extracts the appropriate ruby text from. Surely, there must be data written down somewhere.

Knowing said fact would be useful for automation purposes through use of Word VBA.

Thank you in advance

**Comment by r12a** [comment]
Unfortunately, i don't think we know the answer to this question. Try asking Microsoft.
