### ISSUE TITLE
[questions/qa-who-uses-unicode]  Increased use of UTF-8 on the Web

### ISSUE THREAD

**Issue by macchiati** [w3c/i18n-drafts#272]
[source] (https://www.w3.org/International/questions/qa-who-uses-unicode.en) [en]

W3Tech now puts it at 96+% of the web.

**Comment by r12a** [comment]
I have added a paragraph to that effect at https://w3c.github.io/i18n-drafts/questions/qa-who-uses-unicode.en but i need to solve a technical problem in order to make it live on CVS. Stand by.

**Comment by r12a** [comment]
Fixed.
