### ISSUE TITLE
[questions/qa-indic-graphemes]  Deletion behavior varies widely

### ISSUE THREAD

**Issue by NorbertLindenberg** [w3c/i18n-drafts#275]
[source] (https://w3c.github.io/i18n-drafts/questions/qa-indic-graphemes.en.html) [en]

A side note on this article says “backwards deletion ... will typically delete text character by character, and so may break down conjuncts”.

Deletion behavior varies widely between applications. In testing with a Balinese cluster consisting of seven code points in various apps on macOS, I found that it can take 1, 3, 6, or 7 delete operations to remove the cluster entirely. The most popular option was 3, and appeared to delete UAX 29 extended grapheme clusters, which in Balinese does break down conjuncts.

**Comment by r12a** [comment]
Yes, it's a good point.  I replaced the old text with the following more general sentence.

> Note that forwards and backwards deletion will typically each delete different numbers of characters per keypress, and backwards deletion may break down conjuncts when forward deletion does not.
