### ISSUE TITLE
[questions/qa-indic-graphemes]  Discuss Indic syllabic categories

### ISSUE THREAD

**Issue by NorbertLindenberg** [w3c/i18n-drafts#276]
[source] (https://w3c.github.io/i18n-drafts/questions/qa-indic-graphemes.en.html) [en]

It would be useful to discuss the three categories that the Unicode property Indic_Syllabic_Category uses for viramas: Virama, Pure_Killer, and Invisible_Stacker.

Pure_Killer viramas are always rendered visibly and don’t cause conjunct formation. They generally don’t cause the problems described in this article. (MYANMAR SIGN ASAT appears miscategorized, as it is used in representing the kinzi, a conjunct form.)

Invisible_Stacker viramas always cause conjunct formation, and should never be rendered visibly. Breaking between such viramas and subsequent consonants is always wrong – and unfortunately that’s what applying extended grapheme cluster rules does.

“Virama” viramas are the confusing ones, which are the focus of this article: They sometimes are rendered visibly in a way that breaking after them would be fine, and sometimes they participate in conjunct formation, so that breaking after them causes problems.

**Comment by r12a** [comment]
Thanks, Norbert. I included a summary along these lines in a side panel note.
