### ISSUE TITLE
[articles/lang-bidi-use-cases]  Subsectionning of "Identifying Base Direction of Content" 

### ISSUE THREAD

**Issue by ntounsi** [w3c/i18n-drafts#279]
[source] (https://w3c.github.io/i18n-drafts/articles/lang-bidi-use-cases/index.en) [en]

My comments are about the Section "[Identifying the Base Direction of Content](https://w3c.github.io/i18n-drafts/articles/lang-bidi-use-cases/index.en#bidi_use_case)"
and the grouping of examples.

Instead of  this (sub)sectioning:
```
Identifying the Base Direction of Content
    Getting things to appear in the right place
    Problems with initial Latin text in RTL strings
    Bidirectional text ordering
    Interpreting HTML markup
    Neutral LTR text
    Spill-over effects
    What consumers of strings need to do
    In-string direction changes
```

I suggest the following: 

```
Identifying the Base Direction of Content
   * Getting things to appear in the right place
    	- Problems with initial Latin text in RTL strings
    	- Bidirectional text ordering
    	- Neutral LTR text
    	- Spill-over effects
   * Interpreting HTML markup
   * What consumers of strings need to do
   * In-string direction changes
```

Bring "_Neutral LTR text_" and "_Spill-over effects_" as subsections of "_Getting things..._".
I think all use-case examples can fall into this section: examples requiring Base Direction as well as examples with Isolate/Numerals. 

Another small comment (nothing to do with above).
Paragraph after Fig-11. "_If a bidirectional string is inserted into a LTR context without specifying the RTL base direction for the inserted string, it can produce unreadable text._"
And 'vice versa' ?

**Comment by r12a** [comment]
Thanks Najib. I didn't indent the headings, but i followed the spirit of the suggestion, rearranging the sections. See https://github.com/w3c/i18n-drafts/commit/f93743c75ecc7c18643fe7ba1b3e01a1ea8694f1#diff-906c7ff47cd7c682246c270be1792afc3ab522478848b1dd13cb514e8a670035
