### ISSUE TITLE
[articles/lang-bidi-use-cases]  JSON example may not be natural

### ISSUE THREAD

**Issue by iherman** [w3c/i18n-drafts#281]
[source] (https://w3c.github.io/i18n-drafts/articles/lang-bidi-use-cases/index.en) [en]

Although the JSON example at the beginning is syntactically correct, multiple languages would usually be specified like this:

```
"language": ["en", "he"]
```

rather than

```
"language": "en, he"
```

(The specifications (e.g., in EPUB, in the Publication Manifest, in schema.org) usually say that the value of "language" is a valid language tag, and there may be several of those present.)

**Comment by r12a** [comment]
Thanks, Ivan.  I changed the example as you suggested.
