### ISSUE TITLE
[questions/qa-html-language-declarations]  editorial fix: "title attribute" > "title element"

### ISSUE THREAD

**Issue by fsasaki** [w3c/i18n-drafts#285]
[source] (https://www.w3.org/International/questions/qa-html-language-declarations) [en]

"In some parts of your code you may have a problem. If you have multilingual text in the title element, you cannot mark up parts of the text for different languages because the title attribute only allows characters – no markup. "

"the title attribute" should be "the title element".

@r12a as a side note: do you prefer comments like this, or rather pull requests?

**Comment by r12a** [comment]
thanks @fsasaki.  A PR would be nice, if you are able :)

**Comment by fsasaki** [comment]
Done, hope that this works for you.
