### ISSUE TITLE
[articles/inline-bidi-markup/index]  Linked test needs update

### ISSUE THREAD

**Issue by fsasaki** [w3c/i18n-drafts#292]
[source] (https://w3c.github.io/i18n-drafts/articles/inline-bidi-markup/index.en) [en]
In the section: https://w3c.github.io/i18n-drafts/articles/inline-bidi-markup/index.en#nomarkup
After this paragraph
```
To replicate the effect of the markup described in the example above related to nested base directions, we can use pairs of characters to surround the embedded text. The first character is one of ⁧ U+2067 RIGHT-TO-LEFT ISOLATE (RLI) or ⁦ U+2066 LEFT-TO-RIGHT ISOLATE (LRI). These are placed in the same location as the opening <span dir="..."> tag. The second character is ⁩ U+2069 POP DIRECTIONAL ISOLATE (PDI), and it corresponds to the </span> in the markup. Here's an example
```
There is a link to a test 
https://w3c.github.io/i18n-drafts/articles/inline-bidi-markup/index-data/rle.html
that test does not use U+2067 and U+2069, but U+202B and U+202C. The test should be updated, or a different test should be linked to from the example.

**Comment by r12a** [comment]
Updated. Thanks.
