### ISSUE TITLE
Obsolete document linked to

### ISSUE THREAD

**Issue by brandelune** [w3c/i18n-drafts#305]
https://github.com/w3c/i18n-drafts/blob/94b9db54cf2c1fa41e19eda2c2f8e1b4f0def846/questions/qa-choosing-encodings.en.html#L93

This line links to [Setting encoding in web authoring applications](https://www.w3.org/International/questions/qa-setting-encoding-in-applications) which is out of date.

Wouldn't it be best to instead link to [Handling character encodings in HTML and CSS (tutorial)](https://www.w3.org/International/tutorials/tutorial-char-enc/) which is referenced in the out of date page as the "you may want to try this page" ?

**Comment by brandelune** [comment]
sorry, gh-pages, not 94b9db5.

**Comment by r12a** [comment]
Thanks, fixed in the commit just above.

**Comment by r12a** [comment]
I removed the paragraph entirely, since it's no longer very useful, especially given that there's an example of how to set UTF-8 just after.
