### ISSUE TITLE
[questions/qa-lang-priorities]  BRIEF_TITLE_GOES_HERE

### ISSUE THREAD

**Issue by sjain123nahta** [w3c/i18n-drafts#308]
Hi,

Sounds for me like a more complex issue. Is it possible to open an SAP incident on BC-CTS-LAN component? This needs a deeper investigation.In this incident you can refer to my name and I will then take over and check the issue.

Regards -  [German language classes in Pune](https://www.sevenmentor.com/german-language-classes-in-pune.php)

**Comment by r12a** [comment]
Closing as spam.
