### ISSUE TITLE
[questions/qa-http-and-lang]  Fixes related to HTTP and pragma

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-drafts#310]
[source] (https://www.w3.org/International/questions/qa-http-and-lang) [en]

In https://github.com/whatwg/html/issues/6907#issuecomment-888284213 @annevk said:

> Some of the information in that document seems inaccurate:
> - User agents must obey <meta http-equiv=content-language>, that's not a "can".
> - The HTTP Content-Language response header is used to determine the language of a node, if other information is not available.

I think the first point relates to:

> HTML5 did, however, make a concession for backwards compatibility. If there is a meta element with http-equiv set to Content-Language in the markup, and if there is no language attribute on the html tag, and if the meta element has a value that is a single language tag, then a browser can (not must) use that information to guess at the default language of the text on the page.

**Comment by r12a** [comment]
Fixed the first point in two locations.

Added a link to the initial description of HTTP pointing to the subsection that describes that the language is inferred from the HTTP header if no other information available.

See https://github.com/w3c/i18n-drafts/commit/c9b9b57281d30a2ef7f5a38a0c6bd5b21d4f17db#diff-9c81db3751b018a8cb0850e497b707d7f3c17d28ab554437b84e5e2a13ce66a3

**Comment by annevk** [comment]
Thanks!
