### ISSUE TITLE
[windows-1255] Character 0xCA

### ISSUE THREAD

**Issue by ldelabre** [w3c/i18n-drafts#312]
Hi,
According to https://encoding.spec.whatwg.org/index-windows-1255.txt, character 0xCA (0xCA - 0x80 = 0x4A = 74) should decode as  :
74	0x05BA	ֺ (HEBREW POINT HOLAM HASER FOR VAV)
but in https://www.w3.org/International/tests/repo/encoding/legacy-single-byte-encodings/windows-1255_chars.js, the test case for 0xca is U+FFFD :
"&lt;td class='test' title='0xca->U+FFFD'&gt;Ê&lt;/td&gt;"

Regards,
Ludovic.

**Comment by r12a** [comment]
@ldelabre thanks for the report.  We have taken the (long delayed) decision to no longer support the Encoding tests under /International, and i recently went through and added a label to that effect to all the normally visible entry files (such as https://www.w3.org/International/tests/repo/results/encoding-sb-dec). The message points to the WPT location.  Thank you for prompting us to do this, as we've not had sufficient bandwidth to support this original copy of the tests alongside the version that was ported to WPT.

I'll therefore close this issue.
