### ISSUE TITLE
[questions/qa-html-encoding-declarations]  Closing slash on meta tag

### ISSUE THREAD

**Issue by RobBelics** [w3c/i18n-drafts#315]
[source] (https://www.w3.org/International/questions/qa-html-encoding-declarations) [en]

In your article example markup, there is a closing slash on the meta tags. As I'm sure you know, the closing slash is not specified for HTML self-closing elements. Though it is allowed, no HTML specification calls for a closing slash, it has no meaning, it does nothing, and browsers will ignore it.

**Comment by r12a** [comment]
Indeed.  But it doesn't do any harm either.  This probably reflects the age of this article, written initially well before HTML5 was a thing, and then updated in the early days of HTML when some people were still using XHTML, so it was safer to allow them to copy paste the example code with a slash.  Should we change the examples now, on the assumption that the world has fully moved to HTML5.  Probably.  I'll add to my list of things to do.

(I see some other things in the source code of that article that i'll update at the same time.)

**Comment by r12a** [comment]
This was fixed (for all language versions) in https://github.com/w3c/i18n-drafts/commit/974a0008daca5437ca91d013add2f1377e0c3933
