### ISSUE TITLE
404 for http://tools.ietf.org/html/bcp47

### ISSUE THREAD

**Issue by nathangibson** [w3c/i18n-drafts#321]
https://www.w3.org/International/questions/qa-choosing-language-tags includes the link [2.2.7 Private Use Subtags](http://tools.ietf.org/html/bcp47#section-2.2.7), which yields a 404.

**Comment by r12a** [comment]
Looks like the IETF have been moving things around again.  The correct URL is https://www.rfc-editor.org/rfc/rfc5646.html#section-2.2.7.  We probably need to change several links on that page.

Thanks for the heads up @nathangibson .

**Comment by xfq** [comment]
I have deployed the fix to our website.
