### ISSUE TITLE
[questions/qa-bidi-unicode-controls]: Update sections about browser support for RLI/LRI

### ISSUE THREAD

**Issue by abdnh** [w3c/i18n-drafts#333]
It's stated in [questions/qa-bidi-unicode-controls](https://www.w3.org/International/questions/qa-bidi-unicode-controls) that the RLI/LRI characters are not supported in browsers. This is no longer the case for Firefox, Chrome, and Edge at least, according to my own tests and the test results in https://w3c.github.io/i18n-tests/results/bidi-algorithm#surrounding_text

**Comment by r12a** [comment]
Thanks for raising this.  I'll try to find some time to edit the article.

I'll also try to ping the Safari folks. For reference, see https://github.com/w3c/afrlreq/issues/10

**Comment by r12a** [comment]
I updated the article.

I also pinged the WebKit developers at https://bugs.webkit.org/show_bug.cgi?id=130823.
