### ISSUE TITLE
[qa-http-and-lang] Make practical difference clear between language of document and language of the intended audience

### ISSUE THREAD

**Issue by j9t** [w3c/i18n-drafts#338]
https://www.w3.org/International/questions/qa-http-and-lang promotes the difference between the language of a document and that of the intended audience. That difference is being used as the decisive factor to advise against the use of the `Content-Language` header.

Given how critical this piece of the article is, it’s not clear (enough), what the practical difference is. For example, an English document is usually for English speakers, and even if it’s not (for example, a French language tutorial teaching English), no one uses a different technical way to portray that difference. So the FAQ entry and the entire argument seem to be based on something that has no practical relevance.

(This isn’t to say it is—it seems to. Therefore the suggestion to make this clearer and to support the premise of the argument.)

**Comment by r12a** [comment]
Under the heading "Specifying the text-processing language" is the following link text:

> If you want to better understand the distinction between (1) using file metadata to identify the audience for the document, and (2) specifying the language used for processing content, see the article Types of language declaration.

Perhaps it would be useful to copy that para to the end of the introduction (after the similar para pointing to "Declaring language..."?

**Comment by j9t** [comment]
That could help. Maybe some “TL;DR” would be useful, too (a one-liner following the first mention of “intended audience”).

(Will review said document to check on my concern about the strength of the argument.)
