### ISSUE TITLE
Remove “HTML5 shim”

### ISSUE THREAD

**Issue by j9t** [w3c/i18n-drafts#341]
The I18N pages include the following line ([example](https://github.com/w3c/i18n-drafts/blob/gh-pages/articles/css3-text/index.en.html#L42)):

```
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
```

This shim doesn’t seem needed anymore; worse, the script isn’t available at this location anymore, either.

Happy to prepare a PR for this.

**Comment by r12a** [comment]
Thanks for raising this. I agree. As mentioned elsewhere, these days i usually remove this each time we make a change to a file or prepare for translation, so closing.
