### ISSUE TITLE
[questions/qa-html-language-declarations] Using ISO 639-3 Code in Language Tag

### ISSUE THREAD

**Issue by tadisdef** [w3c/i18n-drafts#351]
[source] (https://www.w3.org/International/questions/qa-html-language-declarations) [en]
Is it acceptable practice to use an ISO 639-3 code (3 letter, not registered with library of congress) for a website in a language undergoing current revival? 
Example: Yola Language (ISO 639-3 "yol") is currently undergoing revitalization but does not have enough modern text to have a ISO 639-2 three letter code or ISO 639-1 two letter code.

**Comment by aphillips** [comment]
Yes. Language tags use a registry of subtags derived from the different parts of ISO639. See https://rfc-editor.org/bcp/bcp47 for details.

**Comment by r12a** [comment]
This web page will tell you what's available: https://r12a.github.io/app-subtags/?find=yola
