### ISSUE TITLE
[questions/qa-personal-names]  Generational name

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#354]
[source] (https://www.w3.org/International/questions/qa-personal-names.en#partorder) [en]

> In the Chinese name 毛泽东 (Mao Ze Dong) the family name is Mao, ie. the first name when reading (left to right). The given name is Dong. The middle character, Ze, is a generational name, and is common to all his siblings (such as his brothers and sister, 毛泽民 (Mao Ze Min), 毛泽覃 (Mao Ze Tan), and 毛泽紅 (Mao Ze Hong)).

I have two comments on this.

First, the given name is Ze Dong instead of Dong. The generational name is also part of the given name, and I don't think it should be taken apart.

Second, this does not usually apply to "all his siblings". It usually only applies to brothers and father's brother's sons, not father's sister's sons, sisters, or other female relatives.  Some families also require females to use the generational name, but AFAIK it is not common.

**Comment by r12a** [comment]
Here are my replies to your comments:

[1] I think this hinges on the definition of 'given name', and unfortunately i don't think there's a particularly unambiguous definition if you look at various sources.  The way i used it here is quite well summed up by the Wikipedia article about [given name](), which says (my emphasis):

> A given name (also known as a **first name** or forename) is **the part of a [personal name](https://en.wikipedia.org/wiki/Personal_name) that identifies a person**, potentially with a [middle name](https://en.wikipedia.org/wiki/Middle_name) as well, and **differentiates that person from the other members of a group** (typically a [family](https://en.wikipedia.org/wiki/Family) or [clan](https://en.wikipedia.org/wiki/Clan)) who have a common [surname](https://en.wikipedia.org/wiki/Surname).

The name Ze doesn't distinguish a person from others in this case, so i didn't refer to it as the 'given' name.

[2] I accept that the generational name doesn't usually apply to all siblings, but in this case it does apply to both his brothers and his sister (ie. all _his_ siblings).  So perhaps there's some additional information that could be added about the use of generational names, but i think that the sentence as it stands is correct.

hth

**Comment by r12a** [comment]
Btw, when translating that section for a Chinese-reading audience, i think you can drop the romanised transcriptions in parentheses.

**Comment by xfq** [comment]
Fair enough. Thank you.
