### ISSUE TITLE
Why translate?

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#369]
There is a multitude of reasons why people contribute to translations. It might be useful to list some of the benefits of translation at https://www.w3.org/International/i18n-drafts/pages/translation.html (or create a new page) to encourage participation.

**Comment by xfq** [comment]
As an example, a few points are listed in the [freeCodeCamp Article Translation Program](https://github.com/freeCodeCamp/news-translation#%E5%8F%82%E4%B8%8E%E6%94%B6%E8%8E%B7):

* Improve your English level and multi-person collaboration experience
* Quickly improve your Git proficiency
* Get GitHub-recognized contributions
* Have the opportunity to be invited to the freeCodeCamp technical conferences
* Meet excellent people in the community and embrace more possibilities for career development

**Comment by r12a** [comment]
Sounds good. Could you submit a PR?  I suggest creating a short section at the end of the page, because most visitors to the page will i think already be interested in translating and therefore will want to see the actionable information straight away.
