### ISSUE TITLE
[questions/qa-scripts]  Please update with additional Unicode RTL scripts

### ISSUE THREAD

**Issue by sven-oly** [w3c/i18n-drafts#373]
[source] (https://www.w3.org/International/questions/qa-scripts) [en]

Note that there are at least 5 additional RTL scripts now in Unicode: [Samaritan](https://en.wikipedia.org/wiki/Samaritan_script), [Mandaic](https://en.wikipedia.org/wiki/Mandaic_alphabet), [Mende Kikakui](https://en.wikipedia.org/wiki/Mende_Kikakui_script), [Adlam](https://en.wikipedia.org/wiki/Adlam_script), [Rohingya](https://en.wikipedia.org/wiki/Hanifi_Rohingya_script). The last three are in Unicode's SMP, so require two 16-bit values (UTF-16) in JavaScript and Java programming languages.
 
Adlam script is becoming widely used for Fula language (code 'ff') in West Africa, and Rohingya is used by that people in addition to other writing systems.

Please consider updating this page with this additional Unicode information.

**Comment by r12a** [comment]
Draft for discussion can be seen at https://deploy-preview-399--i18n-drafts.netlify.app/questions/qa-scripts.en

**Comment by r12a** [comment]
Fixed. See https://www.w3.org/International/questions/qa-scripts.en.html
