### ISSUE TITLE
[articles/ruby/markup]  Links are broken

### ISSUE THREAD

**Issue by upsuper** [w3c/i18n-drafts#38]
[source](http://w3c.github.io/i18n-drafts/articles/ruby/markup.en.html) [en]

It seems most of links in the page are broken. Probably because they point to some pages in "/International" which is not available on github.io.

**Comment by r12a** [comment]
correct.  (I did mention that in the request for review, but since i always get comments about it perhaps i should just change all the links before and after the review.)

**Comment by r12a** [comment]
Ok, all links should now work.  See https://github.com/w3c/i18n-drafts/commit/79a53fd2d645896b5041684106ad13734a3f24cb
I also corrected a few that were pointing to the wrong place, so thanks for the comment!
