### ISSUE TITLE
[articles/definitions-time/index]  Possible typo

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#388]
https://www.w3.org/International/articles/definitions-time/#html5_terms

> **global date and time**
> A 6-digit date, either T or space, a 4-9 digit time (required), a time-zone offset (required) that is Z or +/-2 digits, with optional seconds
> 2016-05-25T21:19:47.123+08
> 2016-05-25 21:19:47-08
> 2016-05-25 21:19:47Z
> 2016-05-25 21:19:00.123+23:45

"A 6-digit date" should probably be "An 8-digit date separated by hyphens".

**Comment by r12a** [comment]
Fixed in https://github.com/w3c/i18n-drafts/commit/ab7656ea508ac4ba4c5779db49f68dd55f6c8143 for en and all translations.
