### ISSUE TITLE
[articles/ruby/markup]  The blank <rt> is not needed in the last example

### ISSUE THREAD

**Issue by upsuper** [w3c/i18n-drafts#39]
[source](http://w3c.github.io/i18n-drafts/articles/ruby/markup.en.html) [en]

In section "Partially overlapping ruby", the article says

> ... since it allows you to leave blank rt elements where needed

but actually the blank rt is not needed at all. You can safely remove the blank rt in this example without changing the behavior, I believe.

**Comment by r12a** [comment]
i believe that's correct.  I left it in, since it makes the example a little clearer for novices, to my mind. But i added a note to say that it's not needed. See https://github.com/w3c/i18n-drafts/commit/1918ae834937125f9f1864b73960115cacdd5feb Thanks.
