### ISSUE TITLE
[articles/idn-and-iri/index] meta description incorrect

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#404]
https://github.com/w3c/i18n-drafts/blob/f3f49f894ee83798fb21f2e22cb585a2e8fd3755/articles/idn-and-iri/index.en.html#L6

The meta description does not match the content of the article (which is about IDNs and IRIs).

**Comment by r12a** [comment]
Indeed. We can do one of the following:
1. remove the meta description element
2. replace the wording with something like: "A high-level introduction to using non-ASCII characters in Web addresses."

**Comment by xfq** [comment]
I sent https://github.com/w3c/i18n-drafts/pull/407 to fix this.
