### ISSUE TITLE
[tutorials/bidi-xhtml/index]  Broken fragment

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#408]
'tightly wrap' in https://www.w3.org/International/tutorials/bidi-xhtml/index#nutshell is broken. The URI fragment was removed in https://github.com/w3c/i18n-drafts/commit/8dcaf5b38d5d52cd47279a04232e9f53eb2d19e8#diff-95d7600ea924d6c139af107474944deab929ae807cbfde051957c5c1eb810aedL285

**Comment by r12a** [comment]
Fixed in https://github.com/w3c/i18n-drafts/commit/1251418934eb49cc37a3f207e112151a07ee6c52
