### ISSUE TITLE
[questions/qa-bidi-css-markup]  Use of markup for bidi text in HTML

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#409]
https://www.w3.org/International/questions/qa-bidi-css-markup#html

> Use markup only. The [CSS Writing Modes](https://www.w3.org/TR/html5/rendering.html#bidi-rendering) specification recommends the use of markup for bidi text in HTML.
> > "If a document language provides markup features to control bidi, authors and users should use those features instead and not specify CSS rules to override them."

The "CSS Writing Modes" URL links to the HTML spec. The link or the link text needs updating.

**Comment by r12a** [comment]
@xfq could you create a PR for this?
