### ISSUE TITLE
Feedback on questions/qa-i18n

### ISSUE THREAD

**Issue by maciejlew** [w3c/i18n-drafts#41]
[source](http://www.w3.org/International/questions/qa-i18n.pl.php) [pl]

Incorrect translation:

'Internacjonalizacja jest często zapisywana jako "l10n", gdzie 10 to liczba liter pomiędzy 'l' i 'n' w angielskim słowie "localization".'

should be:

'Internacjonalizacja jest często zapisywana jako "i18n", gdzie 18 to liczba liter pomiędzy 'i' i 'n' w angielskim słowie "internationalization".'

**Comment by r12a** [comment]
Also now fixed. Thanks again.
