### ISSUE TITLE
[articles/ruby/styling] comments on Japanese word example 

### ISSUE THREAD

**Issue by realskk** [w3c/i18n-drafts#412]
[source] (https://www.w3.org/International/articles/ruby/styling.en.html) [en]

In Fig.13, ruby of "水芝居" becomes "みずばいし", but probably this might be "みずしばい". 

(In addition, "水芝居" dosen't looks popular words. I searched this word in Japanese dictionary, but I can't find it.)

**Comment by r12a** [comment]
Oops. Thanks for spotting that. Should be fixed now.

There was some reason i chose the term 水芝居 (which may not be connected to its use here), but it was for some materials i developed quite a few years ago, and i don't remember the details.
