### ISSUE TITLE
[tutorials/bidi-xhtml/index]  misaligned references to articles

### ISSUE THREAD

**Issue by johnobe** [w3c/i18n-drafts#42]
[source](https://www.w3.org/International/tutorials/bidi-xhtml/#markup) [en]

In the section "Markup for text direction" the first paragraph doesn't seem to be correct.

> In this section we cover the basics of markup for text direction. The first article deals with setting direction at a document and structural level. The second with inline text elements – this is somewhat more complicated than the former, because it is where you have to handle bidirectional text.

The quoted text should reference the second and third articles, respectively, not the first and second. 

I ran the German translation through Google Translate and it appears to have the same issue as well.

**Comment by r12a** [comment]
Thanks for noticing that.  I'll fix it when i get a moment.
