### ISSUE TITLE
[tutorials/language-decl/index]  inquiry about tag for Deutsch / Switzerland

### ISSUE THREAD

**Issue by kingma-sbw** [w3c/i18n-drafts#420]
[source] (https://www.w3.org/International/tutorials/language-decl/) [de]

Wie lautet den Code für Deutsch Switzerland?

**Comment by xfq** [comment]
`de` should do the trick. Use `de-CH` if you want more precision.

**Comment by r12a** [comment]
Or `gsw`. See https://r12a.github.io/app-subtags/index.html?find=swiss
