### ISSUE TITLE
incorrect info in article about http charset

### ISSUE THREAD

**Issue by reschke** [w3c/i18n-drafts#426]
> HTTP 1.1 says that the default charset is ISO-8859-1. 

That's not true. It has been fixed in RFC 7231, 8 years ago, and revised again last year (RFC 9110).

See https://greenbytes.de/tech/webdav/rfc7231.html#rfc.section.B.

**Comment by r12a** [comment]
@reschke which article are you referring to ?

**Comment by r12a** [comment]
Perhaps this one: https://www.w3.org/International/articles/http-charset/index.en ?

**Comment by reschke** [comment]
Yes, that one.

**Comment by aphillips** [comment]
Thank you for the pull request @reschke! We appreciate it.
