### ISSUE TITLE
[articles/typography/fontstyles]  Kai used for emphasis

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#428]
[source] (https://www.w3.org/International/articles/typography/fontstyles.en.html) [en]

> The Kai font style provides calligraphic styles for Chinese characters. It shows notable handwriting features. Kai is mainly used in text that needs to be differentiated from the rest of the content, for example, headlines, references, quotations, and dialogs. (It is rarely used for emphasis, because of its similarity to Song.)

"It is rarely used for emphasis, because of its similarity to Song." is not correct. It is not uncommon, especially in translated foreign language works.

**Comment by r12a** [comment]
Finally fixed. Thanks.
