### ISSUE TITLE
[questions/qa-lang-why]#fonts Inconsistent font style (serif vs. sans, weight)

### ISSUE THREAD

**Issue by Artoria2e5** [w3c/i18n-drafts#43]
> [source](http://www.w3.org/International/questions/qa-lang-why.en.php) [en]
> ![Problem](https://www.w3.org/International/questions/images/ideographs.png)

In this image `zh-*` uses a very thin serif style, while `ko` uses sans of different weights. This can be misleading in a way that it gives readers the impression of how these languages should look like and potentially encourage misuse of such thin serifs in `zh` web pages.

Adobe's [Source Han Sans](https://github.com/adobe-fonts/source-han-sans) provides locale variants for all these four languages (zh-Hans -> CN, zh-Hant -> TW, ja -> JP, ko -> KR), and since it is a single typeface itself noises created by font selection can be elliminated. I personally suggest using this family of fonts for example images.

PS: Windows is very well-known for its bug of generating serif fallbacks for sans families in the Chinese community, and it keeps doing so even with the emergence of Microsoft's Chinese Sans like Microsoft YaHei and Microsoft JhengHei. As a result, nobody actually trusts `sans-serif` for these languages. Using Windows as an example platform is a bad idea for Chinese usage.

**Comment by r12a** [comment]
thanks for the comment. I wanted to keep an example of the default browser behaviour (what you see above is a screen snap), rather than apply  a special font.  I have, however, replaced the image with a new screen snap, taken on the Mac, which although it uses 5 different fonts, looks a little more consistent, despite the clear locale-related and font-related differences.

**Comment by Artoria2e5** [comment]
Mac sounds better to me (at least they know what sans is and won't scare off `font-family: sans-serif` writers……Oh forgot that they use serifs in browsers.)
