### ISSUE TITLE
[questions/qa-floating-times]  

### ISSUE THREAD

**Issue by matial** [w3c/i18n-drafts#44]
[source](http://w3c.github.io/i18n-drafts/questions/qa-floating-times.en.html) [en]

The last paragraph says "But you'll want to use a consistent (or floating) frame of reference when retrieving the record."
It is not clear to me which "record" is meant. Note that this is the only reference to a record in the document.

**Comment by aphillips** [comment]
I rewrote the section in question. @matial please let me know if this clarifies successfully and close if so (or comment further if it does not)
