### ISSUE TITLE
[questions/qa-date-format]  Suggestion for date formats

### ISSUE THREAD

**Issue by luisga158** [w3c/i18n-drafts#443]
[source] (https://www.w3.org/International/questions/qa-date-format.es) [es]

Greetings from Colombia.
First: Thanks for the post [source].
It's very good, the topic is very interesting and very important.

In option 1: Respect for the ISO 8601 standard, it is the most orderly and logical, but it is something that people who do not work in technology, as the article says, is not friendly.

And why is it the best, for me?:
Because when you order them alphabetically, they are ordered chronologically at the same time.

In option 2: We already see the friendly form, and it must vary according to the language, forming groups of language, form and grammar, adapting to the user. (Option 3)
But if you order alphabetically, it is not in chronological order, since the day is first and every month has several days in common, also the months are in letters and the alphabetical order does not correspond to its chronological order.

Taking into account the above, and looking for the most practical and complete.
It occurs to me, the storage of the files with the ISO 8601 standard (So that they are ordered chronologically), and then the friendly format, to give it both order, and the information in a friendly and easy to understand way for the user, which is in option 3, to automate requesting access to the location.
Example: NameOptional-2022_02_20-February 20, 2022-NameOptional

And that was what occurred to me, they tell me, if I can help, they tell me.
A fraternal hug from Colombia

**Comment by r12a** [comment]
Thank you for your comment.  We plan to rewrite that article soon, and i've kept a reference to this issue in the notes for consideration at that time. In the meantime, i'll close this issue.
