### ISSUE TITLE
[articles/vertical-text/index] Misleading Forms test results

### ISSUE THREAD

**Issue by 747** [w3c/i18n-drafts#444]
[source] (https://www.w3.org/International/articles/vertical-text/) [en]

See the pic:
![https://www.w3.org/International/articles/vertical-text/#forms on FF 109](https://user-images.githubusercontent.com/3427854/217420667-d084ae3f-f15b-495c-abfa-f680ea1ee609.png)

Indeed, the description text only mentions `select` and not `option`s, so this might be technically correct, but the latest Firefox behavior is apparently not "as illustrated in the following diagram".

AFAIK it is because the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1170129, which is effectively a regression since FF 68 when the e10s feature is forced on every environment.

**Comment by r12a** [comment]
Thanks for reminding me of this.  I had been intending to clarify it some time ago, but forgot.

Should hopefully be clearer now.

I also added a new section on progress bars, meters, and buttons.

Commit is https://github.com/w3c/i18n-drafts/commit/76d91732e226950fc208c1ce5ffd354cb4a4a3c7
