### ISSUE TITLE
[questions/qa-choosing-encodings]  Encodings that should be avoided

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#456]
[source] (https://www.w3.org/International/questions/qa-choosing-encodings#avoid) [en]

> The HTML5 specification [calls out](https://www.w3.org/TR/html50/document-metadata.html#charset) a number of encodings that you should avoid.

The current HTML Standard doesn't seem to list the encodings. We probably need to update this section a bit.

**Comment by r12a** [comment]
My guess is that this information has been moved to the Encoding spec.

**Comment by xfq** [comment]
It seems to be fixed in https://github.com/w3c/i18n-drafts/pull/461
