### ISSUE TITLE
[questions/qa-byte-order-mark]  Remove reference to next version of Internet Explorer

### ISSUE THREAD

**Issue by btangmu** [w3c/i18n-drafts#465]
[source] (https://www.w3.org/International/questions/qa-byte-order-mark.en.html) [en]

Very accurate and well written. However, this comment should be removed: "It is hoped that the next version of Internet Explorer will ..."

According to Microsoft, "Internet Explorer (IE) is officially retired and out of support as of today, June 15, 2022".

https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/

**Comment by r12a** [comment]
Thanks for the pointer.  I notice also that 2 images are missing. I'll look into it.

**Comment by r12a** [comment]
Done.  I left in some of the note for those few who are interested in historical details.  I also restored the images. Thanks again.

**Comment by btangmu** [comment]
Great, thanks!
