### ISSUE TITLE
Feedback on questions/qa-css-lang

### ISSUE THREAD

**Issue by catchmyfame** [w3c/i18n-drafts#47]
[source](http://www.w3.org/International/questions/qa-css-lang.en.php) [en]

Broken link in the "Longer answer" paragraph. "For more information about support for these selectors see the test results." The test results text links to a dead page at https://www.w3.org/International/tests/html5/css3-selectors-lang/results-lang

**Comment by r12a** [comment]
Should be fixed now. Thanks for pointing it out.
