### ISSUE TITLE
[articles/definitions-time/index]  incremental time mapping

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-drafts#48]
[source](http://w3c.github.io/i18n-drafts/articles/definitions-time/index.en) [en]

> However, incremental time is not usually seen directly by users, but is mapped to a field-based time format for human consumption.

Technically the above quote isn't quite right. Incremental times are usually mapped to local time values (the display value). They may be serialized as field-based times for interchange. So I'd mention both. Perhaps:

> However, incremental time is not usually seen directly by users, but is mapped to a field-based time format for interchange or to local/wall time for human consumption.

**Comment by r12a** [comment]
Changed.
