### ISSUE TITLE
[articles/definitions-time/index]  floating time editorial nits

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-drafts#49]
[source](http://w3c.github.io/i18n-drafts/articles/definitions-time/index.en) [en]

I would maybe change:

> Although, in some parts of the world, the British 11th June starts or ends on what would be Friday or Sunday in Britain, the date given for the event is always Saturday 11 June.

... to be a little clearer about the "floating" nature of it:

> Outside Britain, 11 June starts or ends at a time that would be Friday or Sunday in Britain, the date given for the event is always Saturday 11 June.

Also: 

> Other examples include...

I might include into the list (even though you've already mentioned a specific event that is a birthday, it's all decorated with Capital Letters of Importance) the concept like "user's birth date"

**Comment by r12a** [comment]
Changed. https://github.com/w3c/i18n-drafts/commit/cd62c4386c2b2894946bd782c6800c63fafa4c68
