### ISSUE TITLE
[articles/language-tags/index]  Link to BCP 47 should be updated

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#495]
https://www.w3.org/International/articles/language-tags/index#extension

> If you feel you really need to use these subtags, you should read the [specification](http://www.w3.org/International/core/langtags/rfc3066bis.html), rather than this article.

The specification link is still RFC 4646, but it should be updated to RFC 5646.

**Comment by aphillips** [comment]
No, it should link to the whole thing

https://www.rfc-editor.org/info/bcp47

**Comment by xfq** [comment]
Fixed. Thanks.

**Comment by xfq** [comment]
I uploaded the files to CVS as well.
