### ISSUE TITLE
[questions/qa-css-lang]  zh-TW and zh-CN

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#498]
https://www.w3.org/International/questions/qa-css-lang.en.html#bytheway

> Until recently the codes zh-TW and zh-CN were used to indicate Traditional and Simplified versions of Chinese writing, respectively.

Perhaps it's safe to remove the "until recently" now?

**Comment by r12a** [comment]
How about this:


> Until the <code class="kw" translate="no">zh-Hans</code> and <code class="kw" translate="no">zh-Hant</code> language tags were available, the codes <code class="kw" translate="no">zh-TW</code> and <code class="kw" translate="no">zh-CN</code> were used to indicate Traditional and Simplified versions of Chinese writing, respectively.   This is not actually appropriate because <code class="kw" translate="no">zh-TW</code> indicates the Chinese <em>language</em> spoken in Taiwan, although more than one Chinese language is spoken there. It was also used for Traditional Chinese writing in Hong Kong. Similarly <code class="kw" translate="no">zh-CN</code> really indicates a generic Chinese <em>spoken language</em> used in China (PRC), rather than Simplified Chinese writing. It could refer to Mandarin or any other Chinese language. The same code was also used incorrectly for the Simplified Chinese written in Singapore.

**Comment by xfq** [comment]
I think for Hong Kong, people were using `zh-HK` instead of `zh-TW`. Perhaps we can delete the following sentence?

> It was also used for Traditional Chinese writing in Hong Kong.

**Comment by r12a** [comment]
Ok.
