### ISSUE TITLE
[tutorials/bidi-xhtml/index]  Language name vs script name?

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#501]
[source] (https://www.w3.org/International/tutorials/bidi-xhtml/) [en]

> Right-to-left scripts are used by numerous languages, including Arabic, Hebrew, Pashto, Persian, Sindhi, Syriac, Thaana, Urdu, Yiddish, etc

Most of the names listed here are language names (some are also script names, such as Arabic, Hebrew, and Syriac), but there is one exception, Thaana, which can only represent the script. We should probably change it to Dhivehi (Maldivian).

**Comment by r12a** [comment]
I agree.
