### ISSUE TITLE
[questions/qa-controls]  Broken links

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#502]
[source] (https://www.w3.org/International/questions/qa-controls) [en]

> The control codes in the range U+0000-U+001F are known as the ["C0" range](https://www.w3.org/International/questions/qa-controls#further). This range begins with the NUL (Null) U+0000 control. The control codes in the range U+0080-U+009F are known as the ["C1" range](https://www.w3.org/International/questions/qa-controls#further). DEL (Delete) U+007F is also a control and is adjacent to the beginning of the C1 Range.

The links to C0 and C1 are broken.

**Comment by r12a** [comment]
Looks like they are trying to point to the Further Reading section, which contains links to the Unicode code charts, but we should probably just link directly to the charts, instead.
