### ISSUE TITLE
[articles/definitions-time/index]  zone offset

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-drafts#51]
[source](http://w3c.github.io/i18n-drafts/articles/definitions-time/index.en) [en]

Zone offsets other than 30 and 45 minutes can also exist, including historically. So I would relax the text slightly to say something like:

> Usually offsets are at hour intervals from UTC, but offsets can also be irregular, such as including an additional 30 or 45 minute difference.

**Comment by r12a** [comment]
Changed. https://github.com/w3c/i18n-drafts/commit/cd62c4386c2b2894946bd782c6800c63fafa4c68
