### ISSUE TITLE
[questions/qa-choosing-language-tags]  Broken link

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#515]
https://www.w3.org/International/questions/qa-choosing-language-tags#langsubtag

> You can find the more specific (ie. the encompassed) subtags by searching the registry for `Macrolanguage: <subtag_name>`. Alternatively, the [Language Subtag Lookup](https://r12a.github.io/app-subtags/) tool will automatically list these for a given macrolanguage ([example](https://r12a.github.io/app-subtags/index.php?lookup=ar&submit=Look+up)).

The "example" link is 404.

**Comment by r12a** [comment]
The .php needs to be replaced by .html
