### ISSUE TITLE
[questions/qa-bidi-controls]  CSS shim link broken

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#518]
[source] (https://www.w3.org/International/questions/qa-bidi-controls#reasons) [en]

> Currently, the adoption of those new control codes is lagging in browsers, whereas isolation can be applied already using markup. (At the moment you can use a [CSS shim](https://www.w3.org/International/articles/inline-bidi-markup/index#cssshim), or dedicated elements such as bdi, but browsers are also working on applying isolation to the use of the dir attribute by default.)

The CSS shim link seems broken.

**Comment by aphillips** [comment]
The text is also somewhat stale?

**Comment by r12a** [comment]
I suggest replacing the following:

> Another, hopefully temporary, issue at the time of writing is that the Unicode Consortium and the W3C recommend applying isolation to embedded ranges of text where the base direction is changed. This means that you should use the RLI, LRI and PDI control codes, rather than the RLE, LRE and PDF ones. Currently, the adoption of those new control codes is lagging in browsers, whereas isolation can be applied already using markup. (At the moment you can use a [CSS shim](https://www.w3.org/International/articles/inline-bidi-markup/index#cssshim), or dedicated elements such as bdi, but browsers are also working on applying isolation to the use of the dir attribute by default.)

with 

> The Unicode Consortium and the W3C recommend applying isolation to embedded ranges of text where the base direction is changed. This means that you should use the RLI, LRI and PDI control codes, rather than the RLE, LRE and PDF ones.

**Comment by xfq** [comment]
Yes, that looks good to me. I'll raise a PR with `git commit --author=r12a`.
