### ISSUE TITLE
[articles/definitions-time/index]  mention "summer time" in title

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-drafts#52]
[source](http://w3c.github.io/i18n-drafts/articles/definitions-time/index.en) [en]

The section heading is just "Daylight Savings Time". But in many parts of the world (ahem!) it is called "Summer Time" instead. Mention both in the section title?

**Comment by r12a** [comment]
Well, i mention it immediately at the start of the section. Usually, for specs we refer to DST, which is why i left the title as is. https://github.com/w3c/i18n-drafts/commit/cd62c4386c2b2894946bd782c6800c63fafa4c68
