### ISSUE TITLE
[articles/definitions-time/index]  outdated link to Olson database

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-drafts#53]
[source](http://w3c.github.io/i18n-drafts/articles/definitions-time/index.en) [en]

The link in the document is to the old twinsun site.

IANA took over the time zone database (`zoneinfo`) a couple years ago (BCP175). 

The link should go here: https://www.iana.org/time-zones

We should update the WG note for this too....

**Comment by r12a** [comment]
Fixed.  https://github.com/w3c/i18n-drafts/commit/cd62c4386c2b2894946bd782c6800c63fafa4c68
