### ISSUE TITLE
[tutorials/language-decl/index]  About HTML5 polyglot document

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#540]
https://www.w3.org/International/tutorials/language-decl/index#nutshell

> If this is XHTML 1.x or an HTML5 polyglot document served as XML, you should also use the `xml:lang` attribute (with the same value). If your page is only served as XML, just use the `xml:lang` attribute.

Since this tutorial is about language information, I'm afraid that the word 'polyglot' might be misinterpreted as its meaning in linguistics (like 'an HTML5 document written in several languages'), so we might want to add a link to its definition. If we feel that this is not that important any more (I personally feel so), we can even consider removing this sentence.

**Comment by r12a** [comment]
Suggest linking to https://www.w3.org/TR/html-polyglot/#dfn-polyglot-markup

**Comment by xfq** [comment]
Fixed and copied to CVS. Thank you!
