### ISSUE TITLE
[articles/definitions-time/index]  

### ISSUE THREAD

**Issue by dehildum** [w3c/i18n-drafts#56]
[source](http://w3c.github.io/i18n-drafts/articles/definitions-time/index.en.html) [en]

The floating time example is likely to leave readers with the impression that floating times only apply to dates. I suggest including lunch as a second example to show that this may also apply to hours in the day as well as dates. Lunch is usually at twelve noon no matter what time zone you are in, thus floats depending on where you are.

**Comment by r12a** [comment]
Actually there are two examples that are time related in that section: the time New Year starts, and the meeting time, but i'll consider replacing that with something like lunch or work times.
