### ISSUE TITLE
[questions/qa-bidi-controls]  i18n-html-tech-bidi is outdated

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#568]
[source] (https://www.w3.org/International/questions/qa-bidi-controls) [en]

> Using escapes is also problematic, since the characters that make up an escape can be mangled by editors in bidirectional text. See [Authoring HTML: Handling Right-to-left Scripts](https://www.w3.org/TR/2014/NOTE-i18n-html-tech-bidi-20140603/#bidisource) for more information.

Perhaps we should link to https://www.w3.org/International/questions/qa-bidi-source.en.html instead.

**Comment by r12a** [comment]
> Perhaps we should link to https://www.w3.org/International/questions/qa-bidi-source.en.html instead.

Yes, indeed.  Please do.  There may be one or two other links still lying around that also need this change. We should keep an eye out for them.
