### ISSUE TITLE
[questions/qa-personal-names] Error in "Middle initials" section

### ISSUE THREAD

**Issue by peremen** [w3c/i18n-drafts#58]
The section says like this:

>  People in Korea, who typically do have 3 names but who don't usually initialise them, may be confused about how to deal with such forms.

Typically Koreans do not have middle names. When Korean names are romanized, some prefer placing space only between family name (usually single character) and given name (usually two characters), while others prefer placing spaces between all syllables (all three characters). As a result, when romanizing Korean name "홍길동" those two are accepted:
- Gildong Hong (placed space only between family/given name, currently recommended)
- Gil Dong Hong (placed spaces between all syllables)

I think the latter case was misinterpreted as "having 3 names", instead of "having 3 syllables in names".

[source](https://www.w3.org/International/questions/qa-personal-names) [en]

**Comment by r12a** [comment]
Thanks for the comment. I'll think about how to reword it so that what is meant is clearer.

**Comment by lifthrasiir** [comment]
@r12a Just in case, did you mean the generational name in addition to family and given names? Generational names in Korea are rapidly falling out of favor (and note that there is no generational part in native Korean names "한글 이름"---as opposed to Sino-Korean names "한자 이름"), and even when in use it is considered a part of given name.

**Comment by r12a** [comment]
@lifthrasiir I was indeed thinking of those people who have generational names. To avoid issues, i made the sentence much more general. It now reads: People in other countries who have more than two names and don't usually initialise them may be confused about how to deal with such forms.
