### ISSUE TITLE
[questions/qa-utf8-bom]  Link is not working

### ISSUE THREAD

**Issue by Karsten-Rehberg** [w3c/i18n-drafts#601]
[source] (https://www.w3.org/International/questions/qa-utf8-bom.de.html) [de]

Hello, the link "http://people.w3.org/rishida/blog/?p=102" in this page is no more.

**Comment by r12a** [comment]
PR at https://github.com/w3c/i18n-drafts/pull/604

**Comment by r12a** [comment]
Thanks for the heads up @Karsten-Rehberg.   This should now be fixed.
