### ISSUE TITLE
Mention the Script Resources documents?

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#611]
https://www.w3.org/International/i18n-drafts/pages/languagedev_participation#resources

> These requirements documents can range from the very large [Japanese Layout Requirements](https://w3c.github.io/jlreq/), to small documents that only provide the essential information needed to support the issues raised in the gap-analysis document, such as the [Khmer Layout Requirements](https://w3c.github.io/sealreq/khmer/).

We no longer have the Khmer Layout Requirements document, perhaps we can mention Script Resources here?

**Comment by r12a** [comment]
Fixed by rewriting the last para under Describing Gaps at https://w3c.github.io/i18n-drafts/pages/languagedev_participation.html#resources to incorporate the script resources pages.

**Comment by xfq** [comment]
Thank you!
