### ISSUE TITLE
Language tag for Dutch

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#613]
https://github.com/w3c/i18n-drafts/blob/265ae5f8947e25c36f04269d6fdc60af0e070ed5/articles/typography/linebreak.en.html#L365

```html
 <p>for example in Dutch  <i class="foreignphrase" lang="du">cafeetje</i> → <i class="foreignphrase" lang="du">café-tje</i> and <i class="foreignphrase" lang="du">skiërs</i> → <i class="foreignphrase" lang="du">ski-ers</i>, and in Hungarian <i class="foreignphrase" lang="hu">Összeg</i> → <i lang="hu">Ösz-szeg</i>.</p> 
```

Language tag for Dutch should be `nl` instead of `du`?

**Comment by r12a** [comment]
yes

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/i18n-drafts/commit/e3f81455cab54fdccd071b4ef81a21379775df70
