### ISSUE TITLE
[questions-qa-personal-names]  

### ISSUE THREAD

**Issue by Benzi-Junior** [w3c/i18n-drafts#64]
[source](https://www.w3.org/International/questions/qa-personal-names) [en]

There is an inconsistency in what you claim the ending of Icelandic surnames is 
first you say the ending should be "-sson" or "-sdóttir" based on gender and then in the section on "Variant word forms" say it is "-son" and "-dóttir".

The second form "-son" and "-dóttir" is correct but the fathers (or in the rare case where applicable the mothers) name should be in possessive form which very commonly ends in s but not universally. 

e.g.
The name "Ingi" in possessive form is "Inga" so the children of Ingi would be 
"Ingason" or "Ingadóttir" **not** "Ingisson" or "Ingisdóttir"

(Sidenote; "Inga" the possesive form of "Ingi" is a homonym of a female name "Inga" whose possessive form is "Ingu" and these should not be confused)

**Comment by rebecaruiz** [comment]
Hello again at last! This summer it was imposible for me to contribute. I
just asked my Icelandic-Spanish family.

**Comment by r12a** [comment]
Thanks for mentioning that inconsistency. Now fixed.
