### ISSUE TITLE
articlelist.fr: translating a link to French

### ISSUE THREAD

**Issue by notabene** [w3c/i18n-drafts#72]
Hi,

In articlelist.fr the link ‘Declaring language in HTML’ should be titled ‘Déclarer la langue en HTML’ as it's translated in questions/qa-html-language-declarations.fr

I would have done it myself but articlelist is not on github it seems.

Cheers,
Stephane

**Comment by r12a** [comment]
Thanks @notabene, i forgot to run the update process. Now fixed.
