### ISSUE TITLE
[articles/vertical-text]  Making RTL text top to bottom

### ISSUE THREAD

**Issue by khaledhosny** [w3c/i18n-drafts#81]
[source] (https://w3c.github.io/i18n-drafts/articles/vertical-text.en) [en]

It somehow feels wrong to have vertical RTL text to flow from bottom to top, is there a way in CSS to make RTL text to flow from top to bottom? If so it would be nice to mention it somewhere in the article.

**Comment by ntounsi** [comment]
Which of the following do you think is wrong, (a) or (b) ?
![untitled2](https://cloud.githubusercontent.com/assets/15004708/23760184/ded8ef34-04e6-11e7-9dde-afa471d25476.jpg)

I suspect both are possible.

**Comment by r12a** [comment]
Either of these is possible using sideways-lr or sideways-rl.  I suspect @khaledhosny is talking about the direction of arabic text when using vertical-rl or vertical-lr, ie. with mixed orientations for CJK and Arabic characters.  @khaledhosny i believe the current default is what was concluded after a good deal of discussion in CSS. It makes sense in that if you had both Latin and Arabic text in the vertical line, the tops of the characters would be pointing in different directions if the arabic flowed downwards.  Actually having RTL flow from bottom upwards is exactly the same as what happens for horizontal text in terms of the interaction between latn and arab scripts, text wrapping, etc – for example, if you rotate the page on which it's printed to the left, it will look like ordinary horizontal bidi text and behave in the same way.

**Comment by khaledhosny** [comment]
@ntounsi If I’m setting Arabic vertically I’d want it to flow like (a) not (b), which I believe how historically Arabic was written vertically.

@r12a 
I think `writing-mode: sideways-lr;` for Arabic is what I looking for, but it wasn’t very clear from the Article so I thought it would be a good idea to make it more clear there (and may be also explain why these two values are currently at risk of being dropped).

I can understand how the current default would be easier for implementations, though I don’t personally agree that it is a good default since mixing Arabic with Latin is not the only way Arabic would be used. But I can live what that as long as there is a way to override it. It seems that `writing-mode: sideways-lr;` will require explicitly tagging the Arabic text, which is not very ideal, but I don’t know if there is other way that does not require explicit tagging.

**Comment by ntounsi** [comment]
@khaledhosny. Aside from the point you are discussing.
I think both (a) and (b) should be possible. Think about the side of books on a bookshelf. In general English books titles read top down, and (some) French books titles read bottom up. Hence my examples. (Yet another countries dependent style of writing?)

Here is a picture of the side of a book in French:
https://app.box.com/s/i4j6xx6kn6gu5nt2ha5ynno7qemoxlq4
The French title reads bottom to top, so the Arabic translation reads top to bottom, just as you expect it.

**Comment by khaledhosny** [comment]
I just checked a ten random Arabic book spines from my book shelf, and all of them had the Arabic from top to bottom (this is actually how I tell if a book is placed correctly or upside down), the same for the English books. I did not have any books with mixed text titles, though.

**Comment by asmusf** [comment]
@khaledhosny  For the Latin script, there is not fixed convention for the orientation of book spines. Conventions appear to differ by language, and in some languages, you will find both. (Verified at the nearest bookshelf to where I am writing this).

The default vertical mode should reflect the situation where Arabic is incorporated in body text that is normally, or commonly set vertically (like CJK text or Mongolian), not specialized cases like spines, signage or labels (e.g. along graph axes).
The sideways modes would appear appropriate for the latter.

**Comment by khaledhosny** [comment]
I’m not really arguing about the defaults. The issue is a comment on a draft article requesting that, if possible, the article be expanded a bit to mention different ways a horizontal script can be handled in vertical writing mode. Sorry if this was not clear.

**Comment by r12a** [comment]
Ok, so i added the following paragraph, and reworked the initial para in the same section.

> The vertical- values of writing-mode are really intended for use in setting a normal vertical context for CJK or Mongolian text. On the other hand, if your content is in English and you want some title text to run from bottom to top vertically, say on a book spine or in table header, you would use writing-mode:sideways-lr, not one of the vertical- values. (To make Arabic script text run up the page, you'd use sideways-rl.)

**Comment by ntounsi** [comment]
Related discussion [here](https://github.com/w3c/alreq/issues/102).
