### ISSUE TITLE
[articles/typography/justification]  

### ISSUE THREAD

**Issue by ntounsi** [w3c/i18n-drafts#82]
[source] (https://w3c.github.io/i18n-drafts/articles/typography/justification.en) [en]

About the use of [TATWEEL] (https://w3c.github.io/i18n-drafts/articles/typography/justification.en#arabic)
Since TATWEEL is a "simplistic variant of the kashida technique", I suggest to say also that TATWEEL suits well or better to some simplistic fonts (e.g. where glyphs have almost a flat baseline, like in a typewriter).
For, otherwise, it completely eliminate the typographical aesthetics of a font.

**Comment by r12a** [comment]
Discuss during telecon and noted.
