### ISSUE TITLE
[articles/ruby/index]  Old ruby article redirects out of date

### ISSUE THREAD

**Issue by mwil** [w3c/i18n-drafts#96]
[source] (https://www.w3.org/International/articles/ruby/) [en]

This page is the first hit on Google for "ruby markup", but well outdated. The link therein to more up-to-date information is also outdated (https://w3c.github.io/i18n-drafts/articles/ruby/markup.en). 

It would be good to link the newest page (https://www.w3.org/International/articles/ruby/markup) and maybe try to improve search engine results.

**Comment by r12a** [comment]
I improved the links. Thanks!  

When i get time, i may look for a better solution.

**Comment by r12a** [comment]
Ok, i moved the old article to https://www.w3.org/International/archive/articles/ruby/ and put a redirect in the original location. So hopefully that should do it.
