### ISSUE TITLE
es-005 langtag?

### ISSUE THREAD

**Issue by ryanve** [w3c/i18n-drafts#97]
[`es-005` is mentioned as a langtag for South American Spanish](https://www.w3.org/International/articles/language-tags/#region). However I'm not finding `es-005` in the [iana registry online](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry). Is it a legit langtag?

**Comment by aphillips** [comment]
The registry is for subtags. Any valid subtags can be used to form a language tag. You won't find complete tags in the registry except for grandfathered tags.

005 is a valid subtag, so es-005 is a valid tag. However es-419 is more commonly used. See CLDR. (cldr.unicode.org)

Addison

(Sent from my Fire tablet)


On July 8, 2017, at 5:02 PM, Ryan Van Etten <notifications@github.com> wrote:


es-005 is mentioned as a langtag for South American Spanish<https://www.w3.org/International/articles/language-tags/#region>. However I'm not finding es-005 in the iana registry online<https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry>. Is it a legit langtag?

-

**Comment by ryanve** [comment]
Oh that makes perfect sense and yup I do see 005 in there. Thx @aphillips!

> Type: region
> Subtag: 005
> Description: South America
> Added: 2005-10-16
