### ISSUE TITLE
[articles/definitions-time/index]  

### ISSUE THREAD

**Issue by wsdwl** [w3c/i18n-drafts#98]
[source] (https://www.w3.org/International/articles/definitions-time/index) [en]

I like the definition and most sounds right to me.

My one remark would be that reducing the leap year rule just to the first part is wrong. You should either say, that a leap day is inserted usually every 4 years or include the full explanation with "except when the year is evenly divisible by 100, unless it’s also evenly divisible by 400".

**Comment by r12a** [comment]
@aphillips what should we do here ?

**Comment by aphillips** [comment]
@wsdwl is correct. Having played in this window with text proposals for a few minutes... I think defining the rule makes the most sense. You want a PR? Or just text:

> The Gregorian calendar is the most widely used way of representing civil time. It is a solar calendar, with years usually consisting of 365 days, plus the concept of a "leap year". This adds an additional day every 4 years, except when the year is evenly divisible by 100 (unless the year is also evenly divisible by 400).

I'm resisting the temptation to say that the calendar counts years in the Common Era.

**Comment by r12a** [comment]
Thanks, both. Fixed in https://github.com/w3c/i18n-drafts/pull/259.
